# Ancience

function kitEffect_Ancience_Kill(player: player, event: object):
	set {_attacker} to {_player}
	kitEffect_Ancience({_attacker})

local function kitEffect_Ancience(player: player):
	set {_now} to now
	setKitStats({_player}, "Ancience", {_now})
	apply regeneration 1 to {_player} for 10 seconds replacing existing effect
	playSound("block.vault.open_shutter", 1, 0.85, {_player})
	particleLaunch({_player})
	set {_activenum} to 200
	loop 200 times:
		getKitStats({_player}, "Ancience") is {_now}
		loop all items in {_player}'s inventory:
			name of loop-item contains "Ancience"
			loop-item is not enchanted
			enchant loop-item with sharpness 5
			playSound("block.enchantment_table.use", 1.1, 0.9, {_player})
			particleEnchant({_player})
		if display name of tool of {_player} contains "Ancience":
			chargeActionBar_TimeDisplay({_player}, {_activenum} / 4, 200 / 4, {_activenum})
		subtract 1 from {_activenum}
		wait a tick
	send action bar "" to {_player}
	if getKitStats({_player}, "Ancience") is {_now}:
		loop all items in {_player}'s inventory:
			name of loop-item is "<##866629>Ancience"
			disenchant loop-item



local function particleLaunch(player: player):
	add rgb(126, 214, 91) to {_colors::*}
	add rgb(207, 240, 188) to {_colors::*}
	add rgb(188, 209, 111) to {_colors::*}

	set {_baseloc} to location 1 meter above {_player}
	set {_count} to a random integer between 50 and 70
	loop {_count} times:
		set {_el} to moveRandomLocation({_baseloc}, 1.2)
		set {_color} to a random element out of {_colors::*}
		set {_pow} to a random number between 0.5 and 1
		spawnParticle_Spell(instant_effect, {_color}, {_pow}, {_el})

	set {_count} to a random integer between 20 and 30
	loop {_count} times:
		set {_el} to moveRandomLocation({_baseloc}, 0.5)
		set {_pow} to a random number between 0.5 and 1.5
		set {_vec} to setVector({_baseloc}, {_el}, {_pow})
		spawnParticle_Vector(copper_fire_flame, {_vec}, 1, {_el})

local function particleEnchant(player: player):
	set {_y} to (y-pos of {_player}) + 2
	loop 10 times:
		set {_loc} to aroundEffect({_player})
		set y-pos of {_loc} to {_y}
		spawnParticle(totem_of_undying, {_loc})