# Pursuit

function kitSkill_Assassin_5(player: player):
	toolCT({_player}, "Assassin", 5)
	kitMsg({_player}, "§5追撃を放ちます...")
	set {_baseloc} to location of {_player}
	loop 15 times:
		{_ng} is not set
		set {_tgloc} to location loop-number meters in front of {_baseloc}
		if block at {_tgloc} is not passable:
			set {_ng} to true
			set {_tgloc} to location loop-number - 1 meters in front of {_baseloc}
		else:
			# --- パーティクル演出 ---
			kitEffect_Pursuit_1({_tgloc})
			# -----------------------
			loop all players in radius 1.5 around {_tgloc}:
				kitCheckTeam(loop-player, {_player}, false) is true
				{_tgplayer} is not set
				set {_tgplayer} to loop-player
			if {_tgplayer} is set:
				set {_ng} to true
				set {_tgloc} to location of {_tgplayer}
				set yaw of {_tgloc} to yaw of {_baseloc}
				set pitch of {_tgloc} to pitch of {_baseloc}
				set {_tgloc} to location 1 meters behind {_tgloc}
	teleport {_player} to {_tgloc}
	playSound("entity.player.attack.sweep", 1, 0.6, {_tgloc})
	if {_tgplayer} is set:
		set {_damage} to 2
		if {Stats.%{_tgplayer}%::Pursuit} is set:
			add 2 * {Stats.%{_tgplayer}%::Pursuit} to {_damage}
		kitDamage({_player}, {_tgplayer}, {_damage}, true)
		kitMsg({_player}, "§1%{_tgplayer}% §4にクリーンヒット!")
		message formatted "§4§l痛い! §5斬撃がヒットした..." to {_tgplayer}
		playSound("entity.zombie.break_wooden_door", 1, 2, {_tgplayer})
		# --- ヒット時のパーティクル演出 ---
		# --------------------------------

	



	playSound("block.anvil.land", 1, 2, {_player})
	set {_baseloc} to location 1.5 meters in front of {_player}
	add 1 to y-coordinate of {_baseloc}
	loop all entities in radius 3 around {_baseloc}:
		kitCheckTeam({_player}, loop-entity, false) is true
		set {_damage} to 2
		if {Stats.%loop-entity%::Pursuit} is set:
			add 2 * {Stats.%loop-entity%::Pursuit} to {_damage}
		kitMsg({_player}, "§1%loop-entity% §4にクリーンヒット!")
		message "§4§l痛い! §5追撃がヒットした..." to loop-entity
		playSound("entity.zombie.break_wooden_door", 1, 2, loop-entity)
		drawDot count 1, particle "witchspell", center loop-entity, visibleRange 30
		kitDamage({_player}, loop-entity, {_damage}, true)
	set {_front} to 2.5
	set {_lr} to 0
	set {_length} to 5
	set {_c} to 0
	loop 15 times:
		add 1 to {_c}
		if {_c} is 3:
			set {_c} to 0
			subtract 1 from {_length}
		set {_loc.l} to location {_front} meters in front of {_baseloc}
		set {_loc.l} to location {_lr} meters to the left of {_loc.l}
		set {_loc.r} to location {_front} meters in front of {_baseloc}
		set {_loc.r} to location {_lr} meters to the right of {_loc.r}
		set {_l} to 0
		loop {_length} times:
			set {_loc.l} to location {_l} meters in front of {_loc.l}
			set {_loc.r} to location {_l} meters in front of {_loc.r}
			drawDot count 1, particle "redstone", RGB 50, 0, 0, center {_loc.l}, visibleRange 30, keepFor 0.5 seconds
			drawDot count 1, particle "redstone", RGB 50, 0, 0, center {_loc.r}, visibleRange 30, keepFor 0.5 seconds
			add 0.1 to {_l}
		add 0.2 to {_lr}
		subtract 0.1 from {_front}

# 斬撃(残像) 演出
function kitEffect_Pursuit_1(loc: location):
	set {_baseel} to {_loc}
	set pitch of {_baseel} to 0
	set {_baseel} to location a random number between -0.5 and 0.5 to the left of {_baseel}
	set pitch of {_baseel} to pitch of {_loc}
	add a random number between 0 and 2 to y-coordinate of {_baseel}
	set {_m} to 0
	loop 7 times:
		set {_el} to location {_m} meters in front of {_baseel}
		spawnParticle_DustTransition(rgb(162, 32, 65), rgb(102, 20, 41), 0.5, {_el})
		add 0.5 to {_m}

function kitSkillSub_Assassin_5(victim: player, asn: number):
	set {_now} to now
	set {Stats.%{_victim}%::Pursuit} to {_asn}
	set {Stats.%{_victim}%::PursuitTime} to {_now}
	wait 3 seconds
	if {Stats.%{_victim}%::PursuitTime} is {_now}:
		delete {Stats.%{_victim}%::Pursuit}
		delete {Stats.%{_victim}%::PursuitTime}