# Sleep Arrow

function kitSkill_Assassin_1(player: player):
	delete {_player}'s tool
	shoot a arrow from {_player} at speed 3
	set metadata value "sleep" of shot arrow to "true"

on damage of player with priority LOW:
	damage was caused by projectile
	metadata value "sleep" of projectile is "true"
	setDamageModification_SET(victim, 0)
	kitSleep(victim, 100)
	kitEffectDescription(victim, "§b§l睡眠")