# Rapid Explosion

function kitSkill_Bomber_1(player: player):
	toolCT({_player}, "Bomber", 1)
	kitMsg({_player}, "§6前方に向けて爆風を放ちます!")
	set {_num} to 0
	set {_int} to 1
	set {_pl} to location of {_player}
	loop 20 times:
		add 1 to {_num}
		if {_num} is 4, 8, 12, 16 or 20:
			add 0.5 to {_int}
		set {_loc} to location of block {_num} meters in front of {_pl}
		kitExplosion({_player}, {_int}, {_loc})
		wait a tick