# Pop Burst

import:
	org.bukkit.Material
	org.bukkit.entity.EntityType
	org.bukkit.inventory.ItemStack
	org.bukkit.event.entity.EntityDamageByEntityEvent

options:
	data-pop: "popburst-tnt"
	pop-first-tick: 10
	pop-second-min-tick: 10
	pop-second-max-tick: 30
	data-firework: "popburst-firework"
	firework-damage: 2

function kitEffect_PopBurst(player: player):
	nameCT({_player}, "Pop Burst")
	kitMsg({_player}, "§e弾ける爆弾を投げました!")
	shoot a primed tnt from {_player} at speed 1
	set {_tnt} to shot primed tnt
	setMetadata({_tnt}, "attacker", "%{_player}%")
	setMetadata({_tnt}, "kit-bomber", 2.5)
	setPersistentData({_tnt}, {@data-pop}, false)
	playSound("entity.tnt.primed", 1, 1.5, {_player})
	particleBomb({_tnt})
	setFuseTime({_tnt}, 40)
	loop 40 times:
		{_alr} is not set
		loop all entities in radius 3 around {_tnt}:
			kitCheckTeam(loop-entity, {_player}, false) is true
			{_alr} is not set
			set {_alr} to true
			set {_to} to location of {_tnt}
			set {_to} to vector of {_to}
			set {_from} to location of loop-entity
			set {_from} to vector of {_from}
			set {_vector} to {_from} - {_to}
			set {_vector} to normalized {_vector}
			set velocity of {_tnt} to {_vector}
			setFuseTime({_tnt}, 5)
			setPersistentData({_tnt}, {@data-pop}, true)
		wait a tick

on explosion with priority LOW:
	set {_pop} to getPersistentData(event-entity, {@data-pop})
	stop if {_pop} is not set
	stop if {_pop} is false

	set {_preact} to metadata value "attacker" of event-entity
	set {_act} to {_preact} parsed as player
	set {_loc} to event-location
	effectFirework({_act}, {_loc})

local function effectFirework(player: player, loc: location):
	set {_air} to false
	set {_air} to true if block below {_loc} is passable

	set {_rum} to a random integer between 8 and 10
	loop {_rum} times:
		set {_pow} to a random number between 3 and 8
		set {_vector} to randomVector({_pow})
		if all:
			{_air} is true
			(y of {_vector}) < 0
		then:
			set y of {_vector} to (y of {_vector}) * (-1)
		set {_effloc} to {_loc} ~ {_vector}
		effectBurst({_player}, {_loc}, {_effloc})

local function effectBurst(player: player, from: location, to: location):
	particleTrail({_from}, {_to})
	loop {@pop-first-tick} times:
		wait a tick
	
	set {_r} to a random integer between 0 and 255
	set {_g} to a random integer between 0 and 255
	set {_b} to a random integer between 0 and 255
	set {_color} to rgb({_r}, {_g}, {_b})
	set {_firework} to spawnFireworks_PLAYER({_player}, {_to}, 0, setFireWorksExplosion("ball", {_color}, {_color}, false, false))
	setPersistentData({_firework}, {@data-firework}, true)

	set {_data.firework} to kitFireworkData()
	set {_data.shooter} to kitFireworkDataShooter()
	set {_uuid} to getUUIDString({_player})
	setPersistentData({_firework}, {_data.firework}, true)
	setPersistentData({_firework}, {_data.shooter}, {_uuid})

	set {_rum} to a random integer between 1 and 2
	loop {_rum} times:
		effectFragment({_player}, {_to})

local function effectFragment(player: player, loc: location):
	set {_material} to Material.FIREWORK_STAR
	set {_itemstack} to new ItemStack({_material})
	set {_EntityType} to EntityType.ITEM

	set {_itemEntity} to spawnEntityType({_EntityType}, {_loc})
	{_itemEntity}.setItemStack({_itemstack})

	setGameType({_itemEntity})
	setMetadata({_itemEntity}, "undelete", true)
	set {_pow} to a random number between 0.5 and 1.5
	set {_vector} to randomVector({_pow})
	set velocity of {_itemEntity} to {_vector}

	set {_tick} to a random integer between {@pop-second-min-tick} and {@pop-second-max-tick}
	particleDust({_itemEntity}, {_tick})
	loop {_tick} times:
		wait a tick

	set {_exloc} to location of {_itemEntity}
	{_itemEntity}.remove()

	set {_r} to a random integer between 0 and 255
	set {_g} to a random integer between 0 and 255
	set {_b} to a random integer between 0 and 255
	set {_color} to rgb({_r}, {_g}, {_b})
	set {_firework} to spawnFireworks_PLAYER({_player}, {_exloc}, 0, setFireWorksExplosion("burst", {_color}, {_color}, false, false))
	setPersistentData({_firework}, {@data-firework}, true)

	set {_data.firework} to kitFireworkData()
	set {_data.shooter} to kitFireworkDataShooter()
	set {_uuid} to getUUIDString({_player})
	setPersistentData({_firework}, {_data.firework}, true)
	setPersistentData({_firework}, {_data.shooter}, {_uuid})

on EntityDamageByEntityEvent with priority LOW:
	set {_victim} to event.getEntity()
	set {_firework} to event.getDamager()

	set {_data.firework} to kitFireworkData()
	set {_metadata} to getPersistentData({_firework}, {_data.firework})
	if {_metadata} is not true:
		stop
	set {_star} to getPersistentData({_firework}, {@data-firework})
	if {_star} is not set:
		stop
	set {_attacker} to getSummonPlayer({_firework})
	if {_attacker} is not set:
		stop
	if kitCheckTeam({_victim}, {_attacker}, false) is false:
		stop

	setDamageModification_SET({_victim}, {@firework-damage})
	LastKiller({_victim}, {_attacker})
	kitEffectDescription({_victim}, "§4❤2")



local function particleBomb(entity: entity):
	loop 40 times:
		set {_baseloc} to location 0.5 meters above {_entity}
		spawnParticle(lava, {_baseloc})
		wait a tick

local function particleTrail(from: location, to: location):
	set {_basevec} to setVector({_from}, {_to})
	set {_distance} to distance between {_from} and {_to}
	set {_multi} to 2
	set {_addm} to {_distance} / ({@pop-first-tick} * {_multi})
	set {_m} to 0

	loop {@pop-first-tick} times:
		loop {_multi} times:
			add {_addm} to {_m}
			set {_v} to {_basevec} * vector({_m}, {_m}, {_m})
			set {_el} to {_from} ~ {_v}
			spawnParticle(firework, {_el})
		wait a tick

local function particleDust(entity: entity, tick: number):
	loop {_tick} times:
		set {_baseloc} to location 0.5 meters above {_entity}
		set {_pow} to a random number between 0 and 0.5
		set {_v} to randomVector({_pow})

		set {_el} to {_baseloc} ~ {_v}
		chance of 10%:
			spawnParticle(lava, {_el})
			wait a tick
			continue
		
		spawnParticle(smoke, {_el})
		wait a tick