# skill-name: Lunatic Madness
options:
	data-frag: "lunatic-madness-liquid"
	metadata-hit: "lunatic madness - hit"

	effect-tick: 200

on damage of player:
	damage was caused by projectile
	projectile is a snowball
	set {_playerUUID} to getPersistentData(projectile, {@data-frag})
	stop if {_playerUUID} is not set
	set {_player} to getPlayer({_playerUUID})

	setMetadata(victim, {@metadata-hit}, {_player})

on projectile hit:
	projectile is a snowball
	getPersistentData(projectile, {@data-frag}) is set
	kitParticle_LunaticMadness_Splash(location of projectile)



function kitEffect_LunaticMadness(player: player):
	set {_tool} to tool of {_player}
	if {_tool} is enchanted:
		nameCT({_player}, "Lunatic Madness")
		kitEffect_LunaticMadness_Execute({_player}, "Buff")
		stop

	# save effects
	set {_effects::*} to getPotionEffects({_player})
	set {_debuff effects::*} to kitEffect_LunaticMadness_DebuffEffects({_effects::*})

	if {_debuff effects::1} is not set:
		kitMsg({_player}, "§c現在§4§lデバフエフェクト§cを所持していません")
		stop
	set {_debuff types::*} to kitEffect_LunaticMadness_DebuffCheck({_debuff effects::*})

	kitParticle_LunaticMadness({_player})
	kitMsg({_player}, "§5現在付与された§4§lデバフ§5を取り込みました...")

	# clear debuffs from player
	loop {_debuff types::*}:
		{_player}.removePotionEffect(loop-value)
	
	# enchanting item
	loop all items in {_player}'s inventory:
		kitItemAllChecker(loop-item, "Berserker", "Skill", 7) is true
		enchant loop-item with unbreaking 1
	
	# check item whether it was used
	set {_true} to true
	while {_true} is true:
		# check if player has the item
		delete {_possess}
		loop all items in {_player}'s inventory:
			kitItemAllChecker(loop-item, "Berserker", "Skill", 7) is true
			set {_possess} to true
		if {_possess} is not set:  # player no longer have the item
			set {_true} to false
			continue

		# check if item was used
		if getKitStats({_player}, "LunaticMadness") is set:
			set {_execute} to getKitStats({_player}, "LunaticMadness")
			deleteKitStats({_player}, "LunaticMadness")
			set {_true} to false
			continue

		wait a tick
	
	# exception handling
	if {_execute} is not set:
		log "%{_player}% のLunatic Madnessは効果を発動せずに強制終了しました"
		stop
	
	# disenchant
	loop all items in {_player}'s inventory:
		kitItemAllChecker(loop-item, "Berserker", "Skill", 7) is true
		disenchant loop-item

	# execute
	if {_execute} is "Buff":
		kitEffect_LunaticMadness_Buff({_player}, {_debuff effects::*})
	else if {_execute} is "Splash":
		kitEffect_LunaticMadness_Splash({_player}, {_debuff effects::*})
	else:
		log "%{_player}% のLunatic Madnessは適切な効果が指定されていませんでした"
		stop

function kitEffect_LunaticMadness_LeftClick(player: player, event: object):
	set {_tool} to tool of {_player}
	{_tool} is enchanted
	nameCT({_player}, "Lunatic Madness")
	kitEffect_LunaticMadness_Execute({_player}, "Splash")

local function kitEffect_LunaticMadness_DebuffEffects(effects: potion effects) :: potion effects:
	# create debuff lists
	add "slowness" parsed as potion effect type to {_debuffs::*}
	add "mining fatigue" parsed as potion effect type to {_debuffs::*}
	add "instant damage" parsed as potion effect type to {_debuffs::*}
	add "nausea" parsed as potion effect type to {_debuffs::*}
	add "blindness" parsed as potion effect type to {_debuffs::*}
	add "hunger" parsed as potion effect type to {_debuffs::*}
	add "poison" parsed as potion effect type to {_debuffs::*}
	add "wither" parsed as potion effect type to {_debuffs::*}
	add "glowing" parsed as potion effect type to {_debuffs::*}
	add "darkness" parsed as potion effect type to {_debuffs::*}
	add "bad omen" parsed as potion effect type to {_debuffs::*}

	# check debuffs from effect list
	loop {_effects::*}:
		set {_efftype} to effectType(loop-value)
		if {_debuffs::*} contains {_efftype}:
			add loop-value to {_returns::*}
	
	return {_returns::*}


local function kitEffect_LunaticMadness_DebuffCheck(effects: potion effects) :: potion effect types:
	loop {_effects::*}:
		set {_efftype} to effectType(loop-value)
		add {_efftype} to {_returns::*}
	
	return {_returns::*}

local function kitEffect_LunaticMadness_Execute(player: player, type: text):
	setKitStats({_player}, "LunaticMadness", {_type})

local function kitEffect_LunaticMadness_Buff(player: player, effects: potion effects):
	set {_tier} to size of {_effects::*}
	set {_tier} to 3 if {_tier} > 3
	set {_time} to {@effect-tick}
	
	kitParticle_LunaticMadness_Buff({_player})

	applyEffect({_player}, strength, {_tier}, {_time}, true)
	applyEffect({_player}, regeneration, {_tier}, {_time})

	kitMsg({_player}, "§5デバフを§4§l自分の力§5へと変換した...")

local function kitEffect_LunaticMadness_Splash(player: player, effects: potion effects):
	kitMsg({_player}, "§5デバフ§cを§4液体§cとして撒き散らします!")
	playSound("item.bucket.empty_lava", 1, 0.85, {_player})

	set {_time} to {@effect-tick}
	loop {_effects::*}:
		add 1 to {_count}

		# type
		set {_type} to effectType(loop-value)
		set {_effect-types::%{_count}%} to {_type}

		# tier
		set {_tier} to effectTier(loop-value)
		set {_effect-tiers::%{_count}%} to {_tier}
	
	set {_baseloc} to location 1.5 meters above {_player}
	set {_basevec} to {_baseloc}.getDirection()
	loop 20 times:
		set {_add.x} to a random number between -0.3 and 0.3
		set {_add.y} to a random number between -0.3 and 0.3
		set {_add.z} to a random number between -0.3 and 0.3
		set {_vec} to {_basevec} + vector({_add.x}, {_add.y}, {_add.z})
		set {_fromshoot} to {_baseloc}
		{_fromshoot}.setDirection({_vec})

		shoot a snowball from {_fromshoot} at speed 0.75
		set {_ball} to shot snowball
		setShooter({_ball}, {_player})
		set {_uuid} to uuid of {_player}
		set {_uuidString} to "%{_uuid}%"
		setPersistentData({_ball}, {@data-frag}, {_uuidString})
		set item of {_ball} to magma block
		kitParticle_LunaticMadness_Liquid({_ball})
	
	set {_enable} to true
	loop 200 times:
		if {_enable} is false:
			continue

		loop all players:
			{_hit.%uuid of loop-player%} is not set
			getMetadata(loop-player, {@metadata-hit}) is {_player}
			set {_hit.%uuid of loop-player%} to true
			loop {_effect-types::*}:
				set {_index} to loop-index
				applyEffect(loop-player, {_effect-types::%{_index}%}, {_effect-tiers::%{_index}%}, {_time})
			message "§4赤い液体に含まれていた§5§lデバフエフェクト§4を食らってしまった!" to loop-player
			kitParticle_LunaticMadness_Hit(loop-player)
			deleteMetadata(loop-player, {@metadata-hit})
		
		set {_projcount} to 0
		loop all projectiles:
			set {_projData} to getPersistentData(loop-projectile, {@data-frag})
			continue if {_projData} is not set
			set {_projPlayer} to getPlayer({_projData})
			{_projPlayer} is {_player}
			add 1 to {_projcount}
		if {_projcount} is 0:
			set {_enable} to false
			continue

		wait a tick
			


local function kitParticle_LunaticMadness(player: player):
	playSound("entity.ender_dragon.ambient", 1, 1.6, {_player})
	set {_baseloc} to location 1 meter above {_player}
	loop 100 times:
		set {_el} to {_baseloc}
		chance of 30%:
			add a random number between -1 and 1 to x of {_el}
			add a random number between -1 and 1 to y of {_el}
			add a random number between -1 and 1 to z of {_el}
		spawnParticle(crimson_spore, {_el})

local function kitParticle_LunaticMadness_Buff(player: player):
	playSound("entity.wither.break_block", 1, 0.65, {_player})
	loop 30 times:
		set {_el} to aroundEffect({_player})
		spawnParticle_Block(magma block, {_el})
	
	set {_y} to 0
	set {_color.g} to 255
	loop 11 times:
		set {_baseloc} to location of {_player}
		set {_rad} to 0
		loop 8 times:
			set {_el} to {_baseloc}
			add 360 / 8 to {_rad}
			add 0.5 * sin({_rad}) to x of {_el}
			add 0.5 * cos({_rad}) to z of {_el}
			add {_y} to y of {_el}
			spawnParticle_Dust(rgb(255, {_color.g}, 0), 1, {_el})

		subtract 23 from {_color.g}
		add 0.2 to {_y}
		wait a tick

local function kitParticle_LunaticMadness_Liquid(proj: entity):
	loop 200 times:
		set {_exist} to false
		loop all projectiles:
			loop-projectile is {_proj}
			set {_exist} to true
		if {_exist} is false:
			stop
		spawnParticle(lava, location of {_proj})
		wait a tick

local function kitParticle_LunaticMadness_Hit(player: player):
	playSound("entity.witch.drink", 1, 0.85, {_player})
	loop 30 times:
		set {_el} to aroundEffect({_player})
		spawnParticle(landing_lava, {_el})
	
	set {_y} to 2
	set {_color.r} to 255
	loop 11 times:
		set {_baseloc} to location of {_player}
		set {_rad} to 0
		loop 8 times:
			set {_el} to {_baseloc}
			add 360 / 8 to {_rad}
			add 0.5 * sin({_rad}) to x of {_el}
			add 0.5 * cos({_rad}) to z of {_el}
			add {_y} to y of {_el}
			spawnParticle_Dust(rgb({_color.r}, 0, 0), 1, {_el})

		subtract 23 from {_color.r}
		subtract 0.2 from {_y}
		wait a tick

local function kitParticle_LunaticMadness_Splash(loc: location):
	playSound("item.bucket.fill_lava", 0.75, 1.5, {_loc})
	loop 10 times:
		spawnParticle(crimson_spore, {_loc})