# King Shield

options:
	distance: 0.6

function kitSkill_Defender_5(player: player):
	wait 6 ticks
	if {Stats.%{_player}%::King Shield} is not set:
		set {Stats.%{_player}%::King Shield} to 200
	else if {Stats.%{_player}%::King Shield} <= 0:
		loop all items in {_player}'s inventory:
			name of loop-item is "§1King Shield"
			delete loop-item
		stop
	playSound("item.armor.equip_netherite", 1, 1, {_player})
	set {_l} to location of {_player}
	set {_pitch} to pitch of {_l}
	set {_height} to {@distance} * cos({_pitch})
	set {_width} to {@distance} * sin({_pitch})
	set {_l1} to location 2 meters in front of {_l}
	set pitch of {_l1} to 0
	set {_l2} to location {_height} meters below {_l1}
	set {_l3} to location {_height} * 2 meters below {_l1}
	set {_l4} to location {@distance} meters to the left of {_l1}
	set {_l5} to location {_height} meters below {_l4}
	set {_l6} to location {_height} * 2 meters below {_l4}
	set {_l7} to location {@distance} meters to the right of {_l1}
	set {_l8} to location {_height} meters below {_l7}
	set {_l9} to location {_height} * 2 meters below {_l7}
	set {_l10} to location {@distance} * 2 meters to the left of {_l1}
	set {_l11} to location {_height} meters below {_l10}
	set {_l12} to location {_height} * 2 meters below {_l10}
	set {_l13} to location {@distance} * 2 meters to the right of {_l1}
	set {_l14} to location {_height} meters below {_l13}
	set {_l15} to location {_height} * 2 meters below {_l13}
	set {_l16} to location {@distance} * 3 meters to the left of {_l1}
	set {_l17} to location {_height} meters below {_l16}
	set {_l18} to location {_height} * 2 meters below {_l16}
	set {_l19} to location {@distance} * 3 meters to the right of {_l1}
	set {_l20} to location {_height} meters below {_l19}
	set {_l21} to location {_height} * 2 meters below {_l19}
	loop 21 times:
		if loop-number is 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18, 20 or 21:
			set pitch of {_l%loop-number%} to 0
			if loop-number is 2, 5, 8, 11, 14, 17 or 20:
				set {_x} to -1
			else:
				set {_x} to -2
			set {_l%loop-number%} to location {_width} * {_x} meters in front of {_l%loop-number%}
		set pitch of {_l%loop-number%} to {_pitch}
	loop 21 times:
		spawn an armor stand at {_l%loop-number%} with nbt compound from "{Invulnerable:1b,PersistenceRequired:1b,NoBasePlate:1b,NoGravity:1b,Invisible:1b,Marker:1b,Pose:{Head:[%{_pitch}%f,0f,0f]},ArmorItems:[{id:""minecraft:air"",Count:1b},{id:""minecraft:air"",Count:1b},{id:""minecraft:air"",Count:1b},{id:""minecraft:blue_stained_glass_pane"",Count:1b}],HandItems:[{id:""minecraft:air"",Count:1b},{id:""minecraft:air"",Count:1b}],ArmorDropChances:[0.085F,0.085F,0.085F,0.0F]}"
		set metadata value "%{_player}%-shield" of spawned armor stand to "%loop-number%"
		set metadata value "gametype" of spawned armor stand to "Kit"
		if {Stats.%{_player}%::King Shield} < 50:
			set helmet of spawned armor stand to white glass pane
		else if {Stats.%{_player}%::King Shield} < 100:
			set helmet of spawned armor stand to light blue glass pane
		else if {Stats.%{_player}%::King Shield} < 150:
			set helmet of spawned armor stand to cyan glass pane
		set {_sl} to {_l%loop-number%}
		add 1.2 + 0.8 * cos({_pitch}) to y-coordinate of {_sl}
		set pitch of {_sl} to 0
		set {_fm} to 0.8 * sin({_pitch})
		set {_sl} to location {_fm} meters in front of {_sl}
		spawn a slime at {_sl} with nbt compound from "{NoGravity:1b,Size:0.5,PersistenceRequired:1,NoAI:1,Silent:1,DropItem:0,Team:""noCollision"",active_effects:[{id:invisibility,duration:12000,amplifier:0,show_particles:0b}]}"
		set metadata value "%{_player}%-shield" of spawned slime to "%loop-number%"
		set metadata value "gametype" of spawned slime to "Kit"
		set spawned slime's display name to "%{_player}%"
	while {_player} is blocking with shield:
		set {_l} to location of {_player}
		set {_pitch} to pitch of {_l}
		set {_height} to {@distance} * cos({_pitch})
		set {_width} to {@distance} * sin({_pitch})
		set {_l1} to location 2 meters in front of {_l}
		set pitch of {_l1} to 0
		set {_l2} to location {_height} meters below {_l1}
		set {_l3} to location {_height} * 2 meters below {_l1}
		set {_l4} to location {@distance} meters to the left of {_l1}
		set {_l5} to location {_height} meters below {_l4}
		set {_l6} to location {_height} * 2 meters below {_l4}
		set {_l7} to location {@distance} meters to the right of {_l1}
		set {_l8} to location {_height} meters below {_l7}
		set {_l9} to location {_height} * 2 meters below {_l7}
		set {_l10} to location {@distance} * 2 meters to the left of {_l1}
		set {_l11} to location {_height} meters below {_l10}
		set {_l12} to location {_height} * 2 meters below {_l10}
		set {_l13} to location {@distance} * 2 meters to the right of {_l1}
		set {_l14} to location {_height} meters below {_l13}
		set {_l15} to location {_height} * 2 meters below {_l13}
		set {_l16} to location {@distance} * 3 meters to the left of {_l1}
		set {_l17} to location {_height} meters below {_l16}
		set {_l18} to location {_height} * 2 meters below {_l16}
		set {_l19} to location {@distance} * 3 meters to the right of {_l1}
		set {_l20} to location {_height} meters below {_l19}
		set {_l21} to location {_height} * 2 meters below {_l19}
		loop 21 times:
			if loop-number is 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18, 20 or 21:
				set pitch of {_l%loop-number%} to 0
				if loop-number is 2, 5, 8, 11, 14, 17 or 20:
					set {_x} to -1
				else:
					set {_x} to -2
				set {_l%loop-number%} to location {_width} * {_x} meters in front of {_l%loop-number%}
			set pitch of {_l%loop-number%} to {_pitch}
		loop all entities:
			if type of loop-entity is an armor stand:
				metadata value "%{_player}%-shield" of loop-entity is set
				set {_num} to metadata value "%{_player}%-shield" of loop-entity parsed as number
				if {Stats.%{_player}%::King Shield} > 0:
					teleport loop-entity to {_l%{_num}%}
					add nbt compound of "{Pose:{Head:[%{_pitch}%f,0f,0f]}}" to nbt compound of loop-entity
				else:
					delete loop-entity
			else if type of loop-entity is a slime:
				metadata value "%{_player}%-shield" of loop-entity is set
				set {_num} to metadata value "%{_player}%-shield" of loop-entity parsed as number
				if {Stats.%{_player}%::King Shield} > 0:
					set {_sl} to {_l%{_num}%}
					add 1.2 + 0.8 * cos({_pitch}) to y-coordinate of {_sl}
					set pitch of {_sl} to 0
					set {_fm} to 0.8 * sin({_pitch})
					set {_sl} to location {_fm} meters in front of {_sl}
					teleport loop-entity to {_sl}
				else:
					delete loop-entity
		if {Stats.%{_player}%::King Shield} <= 0:
			loop all items in {_player}'s inventory:
				name of loop-item is "§1King Shield"
				delete loop-item
#			loop {Stats.%player%::*}:
#				loop-index contains "KingShield"
#				delete {Stats.%player%::%loop-index%}
		else:
			chargeActionBar({_player}, {Stats.%{_player}%::King Shield} * 0.25, 50)
		wait a tick
	playSound("item.armor.equip_generic", 1, 1, {_player})
	loop all entities:
		if type of loop-entity is an armor stand:
			metadata value "%{_player}%-shield" of loop-entity is set
			delete loop-entity
		else if type of loop-entity is a slime:
			metadata value "%{_player}%-shield" of loop-entity is set
			delete loop-entity

on damage of slime:
	set {_name} to victim's display name parsed as player
	metadata value "%{_name}%-shield" of victim is set
	if kitCheckTeam({_name}, attacker, false) is true:
		if damage was caused by attack, projectile or void:
			playSound("entity.armor_stand.hit", 1, 1, victim)
			set {_dmg} to damage
			set damage to 0
			set {_num} to metadata value "%{_name}%-shield" of victim parsed as number
			subtract {_dmg} from {Stats.%{_name}%::King Shield}
			loop all entities:
				type of loop-entity is armor stand
				metadata value "%{_name}%-shield" of loop-entity is set
				if {Stats.%{_name}%::King Shield} < 50:
					set helmet of loop-entity to white glass pane
				else if {Stats.%{_name}%::King Shield} < 100:
					set helmet of loop-entity to light blue glass pane
				else if {Stats.%{_name}%::King Shield} < 150:
					set helmet of loop-entity to cyan glass pane
		else:
			cancel event
	else:
		cancel event