options:
	prefix: §e[§aKit PvP§e]

aliases:
	shulk = minecraft:red_shulker_box, minecraft:blue_shulker_box, minecraft:yellow_shulker_box, minecraft:lime_shulker_box

command /emjvoidtp <text>:
	permission: sk.admin
	trigger:
		load yml "plugins/skript-yaml/Kit Stages/All Stages.yml" as "KitStages"
		set {_stages::*} to yml list "Stages" from "KitStages"
		unload yml "KitStages"
		if {_stages::*} contains arg 1:
			load yml "plugins/skript-yaml/Kit Stages/%arg 1%.yml" as "MapEdit"
			if yml value "rule" from "MapEdit" is "EmJ":
				set {_loc} to location of block at player
				set yml value "emj-rule.voidtp.x" from "MapEdit" to x-coordinate of {_loc}
				set yml value "emj-rule.voidtp.y" from "MapEdit" to y-coordinate of {_loc}
				set yml value "emj-rule.voidtp.z" from "MapEdit" to z-coordinate of {_loc}
				set yml value "emj-rule.voidtp.yaw" from "MapEdit" to yaw of {_loc}
				set yml value "emj-rule.voidtp.pitch" from "MapEdit" to pitch of {_loc}
				set yml value "emj-rule.voidtp.world" from "MapEdit" to kitWorldNC(arg 1)
				save yml "MapEdit"
				message "{@prefix} §6%arg 1%§7の§bVoid TP地点§7を設定しました" to player
			else:
				message "{@prefix} §cルールが異なっています" to player
		else:
			message "{@prefix} §cそのステージは存在しません" to player

command /emjgembox <text> <text>:
	usage: /emjgembox <team-color> <map-name>
	permission: sk.admin
	trigger:
		load yml "plugins/skript-yaml/Kit Stages/All Stages.yml" as "KitStages"
		set {_stages::*} to yml list "Stages" from "KitStages"
		unload yml "KitStages"
		if {_stages::*} contains arg 2:
			load yml "plugins/skript-yaml/Kit Stages/%arg 2%.yml" as "MapEdit"
			if yml value "rule" from "MapEdit" is "EmJ":
				if targeted block is shulk:
					set {_loc} to location of targeted block
					set yml value "emj-rule.gembox.%arg 1%.x" from "MapEdit" to x-coordinate of {_loc}
					set yml value "emj-rule.gembox.%arg 1%.y" from "MapEdit" to y-coordinate of {_loc}
					set yml value "emj-rule.gembox.%arg 1%.z" from "MapEdit" to z-coordinate of {_loc}
					set yml value "emj-rule.gembox.%arg 1%.yaw" from "MapEdit" to yaw of {_loc}
					set yml value "emj-rule.gembox.%arg 1%.pitch" from "MapEdit" to pitch of {_loc}
					set yml value "emj-rule.gembox.%arg 1%.world" from "MapEdit" to kitWorldNC(arg 2)
					save yml "MapEdit"
					message formatted "{@prefix} §6%arg 2%§7の <%arg 1%>%arg 1% §bGembox §7を設定しました" to player
				else:
					message "{@prefix} §cシュルカーボックスを指定して下さい" to player
			else:
				message "{@prefix} §cルールが異なっています" to player
		else:
			message "{@prefix} §cそのステージは存在しません" to player

command /emjgoal <number> <text>:
	permission: sk.admin
	trigger:
		load yml "plugins/skript-yaml/Kit Stages/All Stages.yml" as "KitStages"
		set {_stages::*} to yml list "Stages" from "KitStages"
		unload yml "KitStages"
		if {_stages::*} contains arg 2:
			load yml "plugins/skript-yaml/Kit Stages/%arg 2%.yml" as "MapEdit"
			if yml value "rule" from "MapEdit" is "EmJ":
				set yml value "emj-rule.goal" from "MapEdit" to arg 1
				save yml "MapEdit"
				message "{@prefix} §6%arg 2%§eのゴールJewel数を§b%arg 1%§eに設定しました" to player
			else:
				message "{@prefix} §cルールが異なっています" to player
		else:
			message "{@prefix} §cそのステージは存在しません" to player