# Skoreの数字が逆転したので こちらで処理

function kitScorePersonal(player: player, slot: number, text: text):
# ##### 調整部分 #####
	# if {_slot} < 8:
	# 	set {_adj} to 8 - {_slot}
	# 	set {_slotnum} to 8 + {_adj}
	# else if {_slot} > 8:
	# 	set {_adj} to {_slot} - 8
	# 	set {_slotnum} to 8 - {_adj}
# ###################
	set slot {_slot} of skoreboard {_player} to {_text}

function kitScoreGlobal(slot: number, text: text):
# ##### 調整部分 #####
	# if {_slot} < 8:
	# 	set {_adj} to 8 - {_slot}
	# 	set {_slotnum} to 8 + {_adj}
	# else if {_slot} > 8:
	# 	set {_adj} to {_slot} - 8
	# 	set {_slotnum} to 8 - {_adj}
# ###################
	loop all players:
		if {Join::%loop-player%} is "Kit":
			set slot {_slot} of skoreboard loop-player to {_text}