command /killmobs <text>:
	permission: sk.admin
	trigger:
		loop all entities:
			type of loop-entity is not player
			getGameType(loop-entity) is (arg 1)
			deleteGameType(loop-entity)
			loop-entity.remove()

command /ping <player=%player%>:
	trigger:
		message formatted "§6%arg 1%§e's ping§d: §a§l%arg 1's ping% §ems" to arg 1

command /head <offline player>:
	permission: sk.admin
	trigger:
		execute console command "/give %player% player_head[profile=""%arg 1%""]"