on damage of player:
	damage was caused by fall
	if {Kit-GameStage::name} is "Thin Barometric Pressure":
		if x-coordinate of victim is between -15 and 15:
			set {_z} to z-coordinate of victim
			if {_z} is between -70 and -64:
				cancel event
			else if {_z} is between 64 and 70:
				cancel event

on walking on barrier:
	gamemode of player is survival
	metadata value "gametype" of player is "Kit"
	if {Kit-GameStage::name} is "Lab", "Towers", "Bridge" or "Honey Comb":
		kill player