import:
	java.lang.Math
	java.lang.Double
	java.util.UUID

	org.bukkit.Bukkit
	org.bukkit.Location
	org.bukkit.entity.Entity
	org.bukkit.util.Vector

# shieldダメージイベント

function spawnShieldEntity(player: player, loc: location) :: entity:
	set {_world} to world of {_loc}
	set {_mobtype} to EntityType.valueOf("SLIME")

	set {_mob} to {_world}.spawnEntity({_loc}, {_mobtype})

	set display name of {_mob} to "%{_player}%"
	setGameType({_mob})
	set {_summonerUUID} to {_player}.getUniqueId().toString()
	setPersistentData({_mob}, "summon-player", {_summonerUUID})
	setPersistentData({_mob}, "shield-entity", true)

	{_mob}.setCustomNameVisible(false)
	{_mob}.setGravity(false)
	{_mob}.setSize(1)
	{_mob}.setPersistent(true)
	{_mob}.setAI(false)
	{_mob}.setSilent(true)
	{_mob}.setInvisible(true)

	set {_scoreboard} to Bukkit.getScoreboardManager().getMainScoreboard()
	set {_team} to {_scoreboard}.getTeam("noCollision")
	{_team}.addEntity({_mob})
	return {_mob}

function isShieldEntity(entity: entity) :: boolean:
	set {_se} to getPersistentData({_entity}, "shield-entity")
	return true if {_se} is true
	return false