import:
	java.util.Base64

on load:
	# それぞれのvalue/signatureの保存
	# [Gray] URL: https://mineskin.org/skins/a0451ad757564510b401134ca31b4227
	set {-tablist::value::gray} to "ewogICJ0aW1lc3RhbXAiIDogMTc4NTY1Njk2NDc2NywKICAicHJvZmlsZUlkIiA6ICJiYzRlZGZiNWYzNmM0OGE3YWM5ZjFhMzlkYzIzZjRmOCIsCiAgInByb2ZpbGVOYW1lIiA6ICI4YWNhNjgwYjIyNDYxMzQwIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY1N2JmZTk2OWEyY2I3MDg5NTM1ODJkMjBkMzQ1OWViY2E4YWY2OTYyNmQ4Y2IyNjViNjE3ZWY0YzNjODhiZjYiCiAgICB9CiAgfQp9"
	set {-tablist::signature::gray} to "IVqazWyVhRPbq3Hgw2kzHct1lIsD6xNMgJ/z6pVbjeqj1ya2VX5gsDLh8i5XjmEm3RgwvIvw7kYqf1R6Qr8kWh2a7pOrPzxd+Y3ENjlSd5bF5b0s8NpoZvEGkzPEPsI3mChr6KVWXhMBpGOO1qsj2VmEPO2AcincRUpgOSsoti8rd0VydEwHj+8YtVjJp5YyH2VCJ0FInQRYLp9l8RbcNIrrTPNz7T4vqi7QAb8ZB7wDmXD15vc2Q+34CdW0CXon8J72P1sAccVfnuUT45N0cbmTD2FKHhmu+7xb4fEw7M9wuc3FZBWp1V8P3k4OUA93+jPxVIYrXJB6VXMUETdqwjPXetbwdRN6SXRtEqaBQwoVS2QUNZ8qSBuMMC4N27Y4IakQkUsvzHL60N9K3Bpmxc6nj0Wa/qAktv167kL0EvQ72RCCuAjxT1TE5XlGJYxBstoDayrmNra7zvfN5vMZqdp+XKsvxVvgTqy2YeuSAONYTEPUi9fkO22Pio8aogCnrvGia8JoMQWAcYntRH9dZBDTbgO2DfsmHW6LiGSGwHOeBb37grrB/9S3g9fXDP5AEns9/m4258FJIUtkBxVRfGtCyMyY0qFHogZ9Nyz0/iJVLn/uIZyxJmSt0/+to3Jyv0OPXro423Vhmq8BYyCO+5rZAI3SGh6Iryl2rjpsj4M="
	# [Red] URL: https://mineskin.org/skins/b41e78d17fed4828b6f5948a2498618f
	set {-tablist::value::red} to "ewogICJ0aW1lc3RhbXAiIDogMTc4NTkyMjI2NzYzNiwKICAicHJvZmlsZUlkIiA6ICI0MmU4MDAxM2I3ZWE0Y2FkYmE1NDJhZWJmNDVhNjBkMyIsCiAgInByb2ZpbGVOYW1lIiA6ICJUYW1hcmlpaWlpaSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81ZjQxYmQwMTUyNGQ1YzU1NDA5NTg0YWM0ZGIyNWUwZjc0ZDRhYWMxNDQxNTNlNmI1NjAxOTQyNTI5MTJkN2EyIgogICAgfQogIH0KfQ=="
	set {-tablist::signature::red} to "WOzjvUtBbyN+mgLa8u4nbIiP6hEFNSv3hpFzvHjfybBsOIUfg3UodTT1vXG+LPp2FuZlh5BcS9N/7yGRtehukDXFWmsHY6EsvesfiHxYmnyw3LtRV6ROnSySbw22cvjCAIyuu43tnnH7Es9BoO4lg0Tt29idtxTfD0WLGNQ0LSrenldIlKtZEEGOgxY6bptDVeO6Fv8xXyjp+/83EHCfECZWuyy2ztB4Vk3FfnkAQg30G4qcSxpAZd/Gy51G+vuP5Px4fWEf+/CYUi9wxtR3GAkHAHl4qGV4glST7kTfihFDhAATeZhcjyW1XIu2nZVBzlnr8Ktq7+L8JLo0UHSDKSoeddOCvO5ksUEA9LM5o/Ex5PhZQTR+xBd7nGLPWJeXoR0smEKldzXgMgw0qs9FDlGDeNnGpGGvKgBz3dhhl7xjLV3gGZ7b+lnV8oVoqSqjbhqIDsm7jMl9Df/RZGVOuAVc0RkBEdkdST9J+bULyQli+rFyNyEVgZYnrSpGU8F79xpf+n0847BKcJ6i4E2vETSlzmiRKQF2URo2V8jiSWHHDMVEBiKdb+2DCQiGm6hDbsPOOUI8vaf8N1aPWbky8kekbnKwEqSXazkBMXzzuDGEui37TnotB+LfjL5awHYG6KWHFVhw1lKUin8g6qNcG9sCWUrh1MXNatgQNO5dtfE="
	# [Blue] URL: https://mineskin.org/skins/5913e00e7b3542f19916f55d0bf40b31
	set {-tablist::value::blue} to "ewogICJ0aW1lc3RhbXAiIDogMTc4NTkyMjM1OTY5MCwKICAicHJvZmlsZUlkIiA6ICI0MDUxNzNiODY0OTM0NTUxOThlOGMzOGJmNmJmNjZiMSIsCiAgInByb2ZpbGVOYW1lIiA6ICJzcGFjZWNhZGV0MTgiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODBhMTgxZTczNzE2MDE2ZDk3Y2MyMWI1MWI0NGQ3NGFkYTBlMzFkZDczYjVkZjZiOWU0NTk2MmI3Mzc5Y2QxMSIKICAgIH0KICB9Cn0="
	set {-tablist::signature::blue} to "KgeTVN9AuMWDjWBRK79Co180+ck2ASJYWXT4U29EQoj4HS3d660C2yL8o4iPVrsSD4TrYDD0lfOGy4o3leKN4eRjOf1bRBBR4Ealg8KEsMw2QUhc8f4aPQo4r3h0R4MOy9onVXDpqRE93keSwL+ypAVRPkyiszxxb4roaD2gRy+sBdc/IOrfU6wnsQNQCZ1tyFcazR52Klp/uopvO5jBsYDmZnKbw6XS16lz1jDFs9xiRsqBkDs793zcIoZurOHKMphP1pxc6uRWnoN3d7kEYy9X9aquB3yc78Z3fDO9ijsmRn55AwCrdOQHPSE4TDx4usO8ieWMG+KwQxAQlXUr+xLOQ2Yu6xmTsk+LO7o7WO/oPueKkRUT+E0y0yT7BCSym01pWWw5ULFkiKHxvgSS/gBG0hNX9uSt1WCVEhl0V5sP4pB5VICsnF7nUokFksrjXrtcJOSLjQWh6OMzT9zgkO9OUAJasa2Q0T79tX1iNTBxETOLbvFAXycGboqZBJRi3k1N1s7T7l+YnMtWtw/1c6UyL6xR14bgX3Q9kJ+mshlLu+2badisLsH3mtaVkI5i0t1vnGFCL3LXKmJZeJhFwlN7PoMftOfY2luJ1gW9v+rYKgDcPHrO8SGnw121o5I+12J1fxRI4MOeGxa/7vYA5mwKsm3XwvCvLQ4Cre58lGs="
	# [Yellow] URL: https://mineskin.org/skins/f0d22d07a91641319946a60e9d3399d3
	set {-tablist::value::yellow} to "ewogICJ0aW1lc3RhbXAiIDogMTc4NTkyMjQxODI1OCwKICAicHJvZmlsZUlkIiA6ICJiMGQ0YjI4YmMxZDc0ODg5YWYwZTg2NjFjZWU5NmFhYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNaW5lU2tpbl9vcmciLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjJhYmEzOGViM2I1ZjcwODI2Y2ZiMTQ3NmQ2ZDc1NjFlYTgwN2MyOWEwOGYwOGRiMzlhZDkxYWU0YjMzNzBjYiIKICAgIH0KICB9Cn0="
	set {-tablist::signature::yellow} to "RILNKFXOnB9oLWuNuIrBM8Bymmd3xvwthapJHX8bObvDCp1epx0ip5iVKgtSjjMPf/aqfef5YVxy8drjQ/EJ8eNcYsHU/ScFhm+8f8x22N67FLIqWh/zyWz58FTlDGD5i+2yQIJnVxFGNvHHEE++cMkYh1e/3XOX1jbpi4k9gmPa+tIGIKx/lsgDxi3vyoCDDpty3uDTQTWorLA8zbB+/GxuYKXYJcy4p7OJN3oRPn3g+XsIyZMX+AL9WyAw7GnxC6KKKHbpQ3gudxr+vq/bDMqhvt3Fe5jh0Xo233m0vpjceW4VEgq92+cmPeSZQf7Zh3De5nQxr5v6fw+1mad4taWawQ+wjNP/nnMpvw6n8JWkYenTJnE6aNw5D+r4yMpmFrMjNWsZp71WMn4YZt9OkNq1ukB45KsTdGBdSlEQN6lo1to/cSPhLqnhuuYkrHB4NS9FlDFbdYQlN6Bdn70OAHaJgZ6G1Vf5l/Eo5z4dC6P7HqJGH8HjpYg0tY6d6lz6/GxQkns5SfD9S4YbNNjULdobjkaYv7uZ4m4xye+y22fp6gu0drZyQxq3lKNOuKdQWxkyMTTNYjxEfqjDD6hp9u1BLx/zEhSTAFURjZ/qy+gbd1N01YPbH7ylxZ25wrj3/N+ZgCZSzax2F+9btiwaf1dAwWXNg6wKBISqi9vfclM="
	# [Green] URL: https://mineskin.org/skins/5e9e786e8811402a89c92b746ec9c186
	set {-tablist::value::green} to "ewogICJ0aW1lc3RhbXAiIDogMTc4NTkyMjQ4MTc4OSwKICAicHJvZmlsZUlkIiA6ICJhYTUwNjRmMDUzOWQ0YmFhYTVkOGMzODllY2JiNGFlMSIsCiAgInByb2ZpbGVOYW1lIiA6ICJ4WF9FbXBsb3ltZW50X1h4IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2UwMGE1NGM3MTExZGM0MmVlNDI5NmJlNmMxMzM2ZmJhZGVkN2E0ZmY0OTIxOTgzYzg0YWQwOWI1OTk1ZWY0MjYiCiAgICB9CiAgfQp9"
	set {-tablist::signature::green} to "KQTK7RM4uXGutXIFxwMOH7vJs/BgRbu4S0ObdsDGXZY8r7UMOHKttO+1S2zFY6t08rp+/Dh6MjHrQOf3kmfDe5sq13X0SPmGfSD28yGMJ/m5mGOc/tKBsMoChtOK5IgJYe1U9csTDO590y+M1pI8X/nsVnLIzliPeahadZm/PMWPf9frN0zpwuAFOR7b3r+OsEGlYQp1i5tXkD93nuq5o3Dz5iJHGXOZ5sh0/GKyAjnK2O8l8ffQMK9NFDNg0/n/Rs7ct4iKjd7USDkFjVuSFgx5XsE27SHeMc8z4As4t05YekR+jrCYOWRgJ503HfQUMdJpxPFri6f08NtrXbLRwFZcmFWubP40f5TuFxSNSKlQYQGbyeSvDsZbgcbPVfJQdisiCG7jITCWqXPb3NqtvOBlWfXy2EZyIjKUXaHaueZ8N9iSvgN0fh/OIRrQKqegX4OUAVhyB1C7y9oxzYOIhY7y+AkgA37N7nMTvG9QXZjIT/eLrBrQS+0MMj0x18VqhfQHbpilwCl3jxXYxNIvWtRlNn3OveabHBSOQYmQYOvkVrgpAk5XMgdxEE/VzGgQzQHq2LlBoy10jS+lC77gPP9djIAYQtYsGW60sKTMFxtLgDzjTTl9FNiYL13pYu4XrbucIF4UozG6HQzOrnVU1YInI7zOs199DZfDTVs5Mnc="

function updateKitTablist():
	set {_game} to {Kit-tochu}
	if {_game} is not true:
		setKitTablist_Lobby()
		stop
	setKitTablist_Match()

local function setKitTablist_Lobby():
	set {_players::*} to all players
	set {_joinedIndex} to 0  # Joinプレイヤー数
	set {_playerList} to createNewArrayList()  # Sorted PlayerList

	# All Players Looping
	for {_lp} in {_players::*}:
		set {_size} to {_playerList}.size()

		if {Join::%{_lp}%} is "Kit":
			if {_size} is not {_joinedIndex}:  # Joinプレイヤーがいる場合、Joinプレイヤーの後ろに追加
				{_playerList}.add({_joinedIndex}, {_lp})
			else:
				{_playerList}.add({_lp})
			add 1 to {_joinedIndex}

		else:
			{_playerList}.add({_lp})

	set {_slot} to 0
	loop ...{_playerList}:
		set {_lp} to loop-value
		set {_colorcode} to "§f"
		if {_slot} < {_joinedIndex}:
			set {_colorcode} to "§6"
		set {_name} to name of {_lp}
		set {_text} to "%{_colorcode}%%{_name}%"

		setTablistSlotFromPlayer({_slot}, {_text}, {_lp})
		add 1 to {_slot}
	
	set {_remain} to 80 - {_slot}
	set {_text} to "                    "

	loop {_remain} times:
		setTablistSlot({_slot}, {_text}, {-tablist::value::gray}, {-tablist::signature::gray})
		add 1 to {_slot}

local function setKitTablist_Match():
	# ゲーム未参加のプレイヤー表示 (観戦者は後方へ) (16 slots)
	set {_players::*} to all players
	set {_playerList} to createNewArrayList()  # Sorted PlayerList (未参加)
	set {_unspecIndex} to 0  # 観戦者でないプレイヤーのIndex

	# All Players Looping
	for {_lp} in {_players::*}:
		set {_size} to {_playerList}.size()

		# 参加済みプレイヤーの場合は別リスト変数に保存してスキップ
		if {Join::%{_lp}%} is "Kit":
			add {_lp} to {_JoinedPlayers::*}
			continue

		if (gamemode of {_lp}) is not spectator:
			if {_size} is not {_unspecIndex}:  # unspecプレイヤーの後ろに追加
				{_playerList}.add({_unspecIndex}, {_lp})
			else:
				{_playerList}.add({_lp})
			add 1 to {_unspecIndex}

		else:
			{_playerList}.add({_lp})

	set {_slot} to 0
	loop ...{_playerList}:
		continue if {_slot} >= 16  # 16スロット以上は表示しない
		set {_lp} to loop-value
		set {_colorcode} to "§7§o"
		if {_slot} < {_unspecIndex}:
			set {_colorcode} to "§f"
		set {_name} to name of {_lp}
		set {_text} to "%{_colorcode}%%{_name}%"

		setTablistSlotFromPlayer({_slot}, {_text}, {_lp})
		set {_usedSlot::%{_slot}%} to true  # 使用済みスロットの保存
		add 1 to {_slot}

	# 各チーム色のタイトル (2/4Teamの取得)
	add "red" to {_teamnames::*}
	add "blue" to {_teamnames::*}
	if {Kit-GameStage::team} is 4:
		add "yellow" to {_teamnames::*}
		add "green" to {_teamnames::*}

	set {_slot.teamtitle::red} to 16
	set {_teamcolor::red} to "§c"
	set {_teamjapanize::red} to "赤"
	set {_slot.teamtitle::blue} to 18
	set {_teamcolor::blue} to "§9"
	set {_teamjapanize::blue} to "青"
	if {Kit-GameStage::team} is 4:
		set {_slot.teamtitle::blue} to 17
		set {_slot.teamtitle::yellow} to 18
		set {_teamcolor::yellow} to "§e"
		set {_teamjapanize::yellow} to "黄"
		set {_slot.teamtitle::green} to 19
		set {_teamcolor::green} to "§a"
		set {_teamjapanize::green} to "緑"
	
	for {_teamname} in {_teamnames::*}:
	
		set {_teamnum} to size of {Kit-team%{_teamname}%::*}

		set {_slot} to {_slot.teamtitle::%{_teamname}%}
		set {_colorcode} to {_teamcolor::%{_teamname}%}
		set {_teamJapanize} to {_teamjapanize::%{_teamname}%}
		set {_text} to "%{_colorcode}%§l§n%{_teamJapanize}%チーム §b(§3§l%{_teamnum}% 人)"
		set {_value} to {-tablist::value::%{_teamname}%}
		set {_signature} to {-tablist::signature::%{_teamname}%}
		setTablistSlot({_slot}, {_text}, {_value}, {_signature})
		set {_usedSlot::%{_slot}%} to true  # 使用済みスロットの保存

		# 予めチームプレイヤーのStartスロットを保存しておく
		set {_slot.%{_teamname}%} to (({_slot.teamtitle::%{_teamname}%}) + 4)

	# 参加中のプレイヤーを一覧表示
	for {_lp} in {_JoinedPlayers::*}:
		set {_team} to {TrueTeam::%{_lp}%}  # teamの取得

		# team情報から必要情報を取得
		set {_slot} to {_slot.%{_team}%}
		continue if {_slot} >= 80  # 80スロット以上は表示しない
		set {_colorcode} to {_teamcolor::%{_team}%}
		set {_name} to name of {_lp}
		set {_text} to "%{_colorcode}%%{_name}%"

		setTablistSlotFromPlayer({_slot}, {_text}, {_lp})
		set {_usedSlot::%{_slot}%} to true  # 使用済みスロットの保存
		add 4 to {_slot.%{_team}%}  # 次のスロットを更新

		# 2teamの場合は別列への移動処理(2列以下)
		if {Kit-GameStage::team} is 2:
			if {_team} is "red":
				if {_slot.%{_team}%} = 80:
					set {_slot.%{_team}%} to 21
			else:
				if {_slot.%{_team}%} = 82:
					set {_slot.%{_team}%} to 23

	# 未使用スロットの非表示処理
	set {_ls} to 0
	set {_text.gray} to "                    "
	set {_value.gray} to {-tablist::value::gray}
	set {_signature.gray} to {-tablist::signature::gray}

	loop 80 times:
		if {_usedSlot::%{_ls}%} is not set:
			setTablistSlot({_ls}, {_text.gray}, {_value.gray}, {_signature.gray})
		add 1 to {_ls}


on join:
	updateKitTablist()
# on quit処理はKit Logout.skに統合