# Katana

options:
	give-amount: 3



function kitEffect_Katana_Kill(player: player, event: object):
	set {_attacker} to {_player}

	load yml "plugins/skript-yaml/Kit Classes/Ninja.yml" as "shuriken.%{_attacker}%"
	set {_Shuriken} to yml value "kititems.Shuriken" from "shuriken.%{_attacker}%"
	unload yml "shuriken.%{_attacker}%"

	loop {@give-amount} times:
		give {_potion} to {_attacker}'s inventory
	send action bar "§b§lShuriken§9を獲得しました!" to {_attacker}