# Katana -双-

on damage of player:
	{Class::%attacker%} is "Ninja"
	if damage was caused by attack:
		if {Stats.%attacker%::Katana-Sou} is true:
			set {_now} to now
			set {_victim} to victim
			set maximum damage delay of {_victim} to 10 ticks
			set {Stats.%attacker%::Katana-Sou-%{_victim}%} to {_now}
			wait 10 ticks
			if {Stats.%attacker%::Katana-Sou-%{_victim}%} is {_now}:
				set maximum damage delay of {_victim} to 20 ticks
		else:
			set maximum damage delay of victim to 20 ticks
	else if {Stats.%attacker%::Katana-Sou} is true:
		set maximum damage delay of victim to 20 ticks

function kitWeapon_Ninja_4(player: player):
	if {Stats.%{_player}%::Katana-Sou} is true:
		if {Stats.%{_player}%::Katana-SouCT} is not set:
			set {Stats.%{_player}%::Katana-SouCT} to true
			set {_loc} to location of {_player}
			set pitch of {_loc} to 0
			playSound("entity.arrow.shoot", 1, 2, {_player})
			drawDot count 1, particle "explosionlarge", center {_player}, visibleRange 30, keepFor 0.5 seconds
			set {_f} to location 10 meters in front of {_loc}
			set {_from} to vector of {_f}
			set {_to} to vector of {_player}
			set {_vector} to {_from} -- {_to}
			set {_vector} to normalized {_vector}
			set velocity of {_player} to {_vector}
			wait a second
			delete {Stats.%{_player}%::Katana-SouCT}
	else:
		set {Stats.%{_player}%::Katana-Sou} to true
		kitMsg({_player}, "§b§l剣の舞§e状態に入ります!")
		playSound("entity.player.attack.crit", 1, 0.5, {_player})
		loop 100 times:
			set {_el} to aroundEffect({_player})
			drawDot count 1, particle "cloud", center {_el}, visibleRange 30
			wait a tick
		kitMsg({_player}, "§b§l剣の舞§cは終わりました")
		delete {Stats.%{_player}%::Katana-Sou}
		toolCT({_player}, "Ninja", 4, "Weapon.main")