# Kagizume

on sneak toggle:
	{Class::%player%} is "Ninja"
	player is not sneaking
	set {_tool} to player's tool
	kitItemAllChecker({_tool}, "Ninja", "Weapon.main", 3) is true
	if checkCT(player, name of {_tool}) is true:
		playSound("entity.blaze.ambient", 1, 1.7, location of player)
		wait a tick
		set {_true} to true
		while {_true} is true:
			if player is not sneaking:
				set {_true} to false
			set {_tool} to player's tool
			if kitItemAllChecker({_tool}, "Ninja", "Weapon.main", 3) is false:
				delete {_true}
			if {_true} is true:
				loop 3 times:
					set {_el} to aroundEffect(player)
					spawnParticle(ash, {_el})
				wait a tick
		if {_true} is false:
			playSound("")
			set {_v} to setVector(location of player, location 5 meters in front of player, 5)
			set velocity of player to {_v}
			loop 10 times:
				if {_hit} is not set:
					loop all players in radius 1.5 around player:
						kitCheckTeam(loop-player, player, false) is true
						{_hit} is not set
						set {_hit} to loop-player
					wait a tick
			if {_hit} is set:
				playSound("")
				kitDamage(player, {_hit}, 3)



function kitWeapon_Ninja_3(player: player):
	if {Stats.%{_player}%::SkillLocation} is set:
		toolCT({_player}, "Ninja", 3, "Weapon.main")
		set {_loc} to {Stats.%{_player}%::SkillLocation}
		set {_dir} to location of {_player}
		set yaw of {_loc} to yaw of {_dir}
		set pitch of {_loc} to pitch of {_dir}
		teleport {_player} to {_loc}
		playSound("entity.illusioner.mirror_move", 0.8, 2, {_player})
	else:
		send action bar "§c§lブロックを指定してください" to {_player}