# Bunshin

function kitEffect_Bunshin(player: player):
	set {_skill} to name of {_player}'s tool
	setCT({_player}, {_skill}, 10)
	kitMsg({_player}, "§2忍法・分身の術!")
	sendTimeBossbar_GREEN({_player}, "Bunshin", 100)
	playSound("block.fire.extinguish", 1, 2, player)
	delete {_player}'s tool
	loop 3 times:
		set {_nbt} to nbt compound from "{IsBaby:0,Silent:1,attributes:[{id:""movement_speed"",base:0.6f}],ArmorItems:[{},{},{id:""minecraft:leather_chestplate"",components:{dyed_color:{rgb:0}},Count:1b},{id:""minecraft:player_head"",components:{profile:%{_player}%},Count:1b}],HandItems:[{},{}],active_effects:[{id:jump_boost,duration:12000,amplifier:2,show_particles:0b}]}"
		spawn a zombie at {_player} with nbt {_nbt}
		set metadata value "gametype" of spawned zombie to "Kit"
		set metadata value "bunshin" of spawned zombie to "%{_player}%"
		set spawned zombie's display name to "%{_player}%"
	kunaiNinjutsu({_player}, "Bunshin")
	wait 5 seconds
	loop all zombies:
		metadata value "bunshin" of loop-zombie is "%{_player}%"
		delete loop-zombie
	send action bar "§7§l分身は解除された!" to {_player}