function sendTimeBossbar_GREEN(player: player, title: text, timetick: number):
	bossbarTimer({_player}, {_title}, "green", {_timetick})

function sendTimeBossbar_RED(players: players, title: text, timetick: number):
	bossbarTimer({_player}, {_title}, "red", {_timetick})

function sendTimeBossbar_YELLOW(players: players, title: text, timetick: number):
	bossbarTimer({_player}, {_title}, "yellow", {_timetick})

function sendTimeBossbar_BLUE(players: players, title: text, timetick: number):
	bossbarTimer({_player}, {_title}, "blue", {_timetick})

function sendTimeBossbar_PINK(players: players, title: text, timetick: number):
	bossbarTimer({_player}, {_title}, "pink", {_timetick})

function sendTimeBossbar_PURPLE(players: players, title: text, timetick: number):
	bossbarTimer({_player}, {_title}, "purple", {_timetick})

function sendTimeBossbar_WHITE(players: players, title: text, timetick: number):
	bossbarTimer({_player}, {_title}, "white", {_timetick})

local function bossbarTimer(player: player, title: text, color: text, timetick: number):
	set {_hashCode} to {_title}.hashCode()
	set {_id} to {_hashCode}.toString()
	# 既に同名のタイマーが存在する場合は進捗のリセット
	if {-bossbarTimer.%{_player}%::%{_id}%} is set:
		set {-bossbarTimer.%{_player}%::%{_id}%} to {_timetick}
		stop

	set {_colorCode} to "§f"
	set {_colorCode} to "§a" if {_color} is "green"
	set {_colorCode} to "§c" if {_color} is "red"
	set {_colorCode} to "§e" if {_color} is "yellow"
	set {_colorCode} to "§b" if {_color} is "blue"
	set {_colorCode} to "§d" if {_color} is "pink"
	set {_colorCode} to "§5" if {_color} is "purple"

	set {_titledisplay} to "%{_colorCode}%§l%{_title}%"
	set {_timedisplay} to timeDisplay_SECOND({_timetick})
	set {_timer.title} to "%{_titledisplay}%§r §b%{_timedisplay}% §3秒"

	if {_color} is "green":
		create bossbar titled {_timer.title} and id {_id} for {_player} with progress 100 with colors green with style solid
	else if {_color} is "red":
		create bossbar titled {_timer.title} and id {_id} for {_player} with progress 100 with colors red with style solid
	else if {_color} is "yellow":
		create bossbar titled {_timer.title} and id {_id} for {_player} with progress 100 with colors yellow with style solid
	else if {_color} is "blue":
		create bossbar titled {_timer.title} and id {_id} for {_player} with progress 100 with colors blue with style solid
	else if {_color} is "pink":
		create bossbar titled {_timer.title} and id {_id} for {_player} with progress 100 with colors pink with style solid
	else if {_color} is "purple":
		create bossbar titled {_timer.title} and id {_id} for {_player} with progress 100 with colors purple with style solid
	else:
		create bossbar titled {_timer.title} and id {_id} for {_player} with progress 100 with colors white with style solid

	set {_maxtick} to {_timetick}
	while {-bossbarTimer.%{_player}%::%{_id}%} is set:
		# タイトル表示用の時間取得
		set {_ticknumber} to {-bossbarTimer.%{_player}%::%{_id}%}
		set {_timedisplay} to timeDisplay_SECOND({_ticknumber})
		set {_timer.title} to "%{_titledisplay}%§r §b%{_timedisplay}% §3秒"
		set bossbar {_id} title to {_timer.title}

		# ボスバー割合の計算
		if {-bossbarTimer.%{_player}%::%{_id}%} > {_maxtick}:
			set {_maxtick} to {-bossbarTimer.%{_player}%::%{_id}%}
		set {_timer.prog} to {_ticknumber} / {_maxtick} * 100
		set bossbar {_id} value to {_timer.prog}

		# 秒数管理変数の更新
		subtract 1 from {-bossbarTimer.%{_player}%::%{_id}%}
		if {-bossbarTimer.%{_player}%::%{_id}%} <= 0:
			delete {-bossbarTimer.%{_player}%::%{_id}%} 
		wait a tick
	remove bossbar {_id}