# Arrow Rain

function kitSkill_Archer_3(player: player):
	toolCT({_player}, "Archer", 3)
	kitMsg({_player}, "§1矢の雨を降らせる卵を発射します...!")
	set {Stats.%{_player}%::ArrowRain} to location of {_player}
	shoot an egg from {_player} at speed 1.5
	set metadata value "arrowegg" of shot entity to "true"
	drawDot count 1, particle "redstone", XYZ 0, 0, 255, center shot entity, visibleRange 32, keepFor 1 seconds
	playSound("entity.arrow.shoot", 1, 0.5, {_player})

on projectile hit:
	projectile is an egg
	metadata value "arrowegg" of projectile is set
	{Stats.%shooter%::ArrowRain} is set
	playSound("entity.generic.burn", 1, 0.5, projectile)
	set {_face} to {Stats.%shooter%::ArrowRain}
	set {_baseloc} to location of block at projectile
	set {_y} to y-coordinate of {_baseloc}
	set y-coordinate of {_face} to {_y}
	set {_dis} to distance between location of {_face} and location of {_baseloc}
	loop 10 times:
		set {_n} to loop-number
		set {_cloud} to location of block {_n} meters upwards {_baseloc}
		drawDot count 1, particle "cloud", center location of {_cloud}, visibleRange 32
		wait a tick
	playSound("entity.lightning_bolt.thunder", 1, 0.5, location of {_sky})
	loop 10 times:
		set {_n} to loop-number
		set {_plus} to {_dis} + {_n}
		set {_sky} to location of block {_plus} meters in front of {_face}
		set y-coordinate of {_sky} to {_y}
		add 10 to y-coordinate of {_sky}
		loop all blocks in radius 5 around {_sky}:
			y-coordinate of loop-block is y-coordinate of {_sky}
			loop-block is air
			add location of loop-block to {_rain::*}
		loop 5 times:
			set {_cloud} to {_sky}
			set {_x} to a random number between -1 and 1
			set {_z} to a random number between -1 and 1
			add {_x} to x-coordinate of {_cloud}
			add {_z} to z-coordinate of {_cloud}
			drawDot count 1, particle "cloud", center location of {_cloud}, visibleRange 32
			loop {_rain::*}:
				chance of 5%:
					shoot an arrow from block at loop-value-3 at speed 3 downward
					set metadata value "arrowdamage" of shot arrow to 2
					set shooter of shot arrow to shooter
					set metadata value "arrowrain" of shot arrow to "%shooter%"
					drawDot count 1, particle "redstone", XYZ 255, 255, 255, center location of loop-value-3, visibleRange 32, keepFor 0.2 seconds
					drawDot count 1, particle "mobspell", XYZ 0, 0, 255, center shot entity, visibleRange 32, keepFor 0.5 seconds
			loop all projectiles in radius 5 around shooter:
				loop-projectile is an arrow
				metadata value "arrowrain" of loop-projectile is "%shooter%"
				delete loop-projectile
			wait a tick
		delete {_rain::*}