# Barrage Arrow

function kitSkill_Archer_5(player: player):
	toolCT({_player}, "Archer", 5)
	set {Stats.%{_player}%::BarrageArrow} to true
	kitMsg({_player}, "§e5秒間§6放つ矢の本数が§e5本§6になります!")
	playSound("entity.zombie.attack_iron_door", 1, 1, {_player})
	drawDot count 3, particle "mobspell", RGB 255, 100, 100, center {_player}, visibleRange 32, keepFor 7 seconds
	wait 5 seconds
	delete {Stats.%{_player}%::BarrageArrow}
	delete {Stats.%{_player}%::DrawTime}
	kitMsg({_player}, "§cBarrage Arrow§dの効果が切れました")

on rightclick holding a bow:
	if {Stats.%player%::BarrageArrow} is true:
		set {Stats.%player%::DrawTime} to 0
		while {Stats.%player%::DrawTime} is set:
			if {Stats.%player%::DrawTime} >= 3:
				stop
			else:
				if {Stats.%player%::BarrageArrow} is true:
					add 0.125 to {Stats.%player%::DrawTime}
					wait a tick
				else:
					delete {Stats.%player%::DrawTime}

on shoot:
	{Stats.%shooter%::BarrageArrow} is true
	{Stats.%shooter%::BarrageNG} is not set
	projectile is an arrow or a spectral arrow
	cancel event
	if {Stats.%shooter%::DrawTime} is set:
		set {_d} to {Stats.%shooter%::DrawTime}
	else:
		set {_d} to 3
	delete {Stats.%shooter%::DrawTime}
	set {Stats.%shooter%::BarrageNG} to true
	playSound("entity.ghast.shoot", 1, 1, shooter)
	set {_l1} to location of head of shooter
	shoot an arrow from {_l1} at speed {_d}
	set shooter of shot projectile to shooter
	drawDot particle "flame", center shot arrow, visibleRange 30, keepFor 1 second
	set {_l2} to {_l1}
	set {_yaw} to yaw of {_l2} - 20
	if {_yaw} < 0:
		set {_yaw} to 360 + {_yaw}
	set yaw of {_l2} to {_yaw}
	shoot an arrow from {_l2} at speed {_d}
	set shooter of shot projectile to shooter
	drawDot particle "flame", center shot arrow, visibleRange 30, keepFor 1 second
	set {_l3} to {_l1}
	set {_yaw} to yaw of {_l3} + 20
	if {_yaw} >= 360:
		set {_yaw} to {_yaw} - 360
	set yaw of {_l3} to {_yaw}
	shoot an arrow from {_l3} at speed {_d}
	set shooter of shot projectile to shooter
	drawDot particle "flame", center shot arrow, visibleRange 30, keepFor 1 second
	set {_l4} to {_l1}
	set {_yaw} to yaw of {_l4} - 40
	if {_yaw} < 0:
		set {_yaw} to 360 + {_yaw}
	set yaw of {_l4} to {_yaw}
	shoot an arrow from {_l4} at speed {_d}
	set shooter of shot projectile to shooter
	drawDot particle "flame", center shot arrow, visibleRange 30, keepFor 1 second
	set {_l5} to {_l1}
	set {_yaw} to yaw of {_l5} + 40
	if {_yaw} >= 360:
		set {_yaw} to {_yaw} - 360
	set yaw of {_l5} to {_yaw}
	shoot an arrow from {_l5} at speed {_d}
	set shooter of shot projectile to shooter
	drawDot particle "flame", center shot arrow, visibleRange 30, keepFor 1 second
#	wait a tick
	delete {Stats.%shooter%::BarrageNG}

on damage:
	damage was caused by projectile
	projectile is an arrow
	if {Stats.%attacker%::BarrageArrow} is true:
		set damage to damage * 0.75