# Death Curse

options:
	charge-tick: 20
	effect-radius: 10

function kitEffect_DeathCurse(player: player):
	set {_SkillTarget} to getKitStats({_player}, "SkillTarget")
	if {_SkillTarget} is not set:
		send action bar "§c§l対象が存在しません!" to {_player}
		stop

	if (health of {_player}) is not (max health of {_player}):
		send action bar "§c§l自身の体力が不足しています!" to {_player}
		stop

	if (health of {_SkillTarget}) is not (max health of {_SkillTarget}):
		send action bar "§c§l対象の体力が不足しています!" to {_player}
		stop

	if kitCheckSpirit({_player}, "Death Curse") is false:
		stop

	nameCT({_player}, "Death Curse")
	set {_tg} to {_SkillTarget}

	set {_memsg1} to kitGhostMessage("§4%{_tg}% §5に死の呪いをかけた...")
	set {_youmsg} to kitGhostMessage("§5%{_player}% §4に死の呪いをかけられてしまった!", true)
	kitMsg({_player}, {_memsg1})
	message formatted {_youmsg} to {_tg}
	set {_health} to 11
	set {_counting} to true
	add {_player} to {_titlePlayers::*}
	add {_tg} to {_titlePlayers::*}

	loop 11 times:
		continue if {_counting} is false

		packetGlowing({_player}, {_tg})
		packetGlowing({_tg}, {_player})
		particleCounting({_player}, {_tg})
		soundCounting({_player}, {_tg})

		subtract 1 from {_health}
		set {_p.health} to health of {_player}
		set {_t.health} to health of {_tg}
		set health of {_player} to {_health} if {_p.health} > {_health}
		set health of {_tg} to {_health} if {_t.health} > {_health}
		LastKiller({_tg}, {_player})
		set {_title} to "§4§l§k! §5§l%{_health}% §4§l§k!"
		set {_subtitle} to kitGhostMessage("§0滅殺呪術発動中", true)
		sendTitle({_titlePlayers::*}, {_title}, {_subtitle}, 1 second, 0.1 seconds, 0.1 seconds)

		loop 20 times:
			continue if {_counting} is false
			# player check
			if all:
				kitCheckAlive({_player}) is false
				getKitStats({_player}, "Heautoscopy") is not set
			then:
				set {_counting} to false
				set {_l} to location of {_player}
				add {_l} to {_deathPoints::*}
			# target check
			if all:
				kitCheckAlive({_tg}) is false
				getKitStats({_tg}, "Heautoscopy") is not set
			then:
				set {_counting} to false
				set {_l} to location of {_tg}
				add {_l} to {_deathPoints::*}
			continue if {_counting} is false
			wait a tick

	particleCharge({_deathPoints::*})
	soundCharge({_deathPoints::*})

	loop {@charge-tick} times:
		wait a tick

	for {_l} in {_deathPoints::*}:
		effectExplosion({_player}, {_l})

local function effectExplosion(player: player, loc: location):
	particleExplosion({_loc})
	soundExplosion({_loc})
	set {_memsg} to kitGhostMessage("§4滅殺呪術 §0が発動しました", true)
	message formatted {_memsg} to {_player}

	loop all entities in radius {@effect-radius} around {_loc}:
		kitCheckTeam({_player}, loop-entity, false) is true
		particleCursed(loop-entity)
		soundCursed(loop-entity)
		
		if checkEntityType(loop-entity, player) is false:
			set health of loop-entity to 0
			continue

		if getKitClass({_player}) is "Ghost":
			set {_youmsg} to kitGhostMessage("§8即死効果を無効化しました", true)
			message formatted {_youmsg} to {_tg}
			continue

		LastKiller(loop-entity, {_player})
		set {_youmsg} to kitGhostMessage("§5呪い殺されてしまった...", true)
		message formatted {_youmsg} to loop-entity
		set health of loop-entity to 0



local function particleCounting(player: player, target: player):
	add rgb(224, 29, 29) to {_colors.flash::*}
	add rgb(192, 10, 55) to {_colors.flash::*}
	add rgb(223, 59, 10) to {_colors.flash::*}

	add rgb(80, 6, 6) to {_colors.dust::*}
	add rgb(97, 13, 34) to {_colors.dust::*}
	add rgb(112, 45, 24) to {_colors.dust::*}

	add rgb(110, 17, 17) to {_colors.spell::*}
	add rgb(121, 29, 52) to {_colors.spell::*}
	add rgb(114, 46, 25) to {_colors.spell::*}

	set {_baseloc.1} to location 1 meter above {_player}
	set {_baseloc.2} to location 1 meter above {_target}

	loop 2 times:
		set {_base} to {_baseloc.%loop-number%}
		set {_color} to a random element out of {_colors.flash::*}
		spawnParticle_Color(flash, {_color}, {_base})

		set {_count} to a random integer between 10 and 15
		loop {_count} times:
			set {_pow} to a random number between 0.5 and 1
			set {_v} to randomVector({_pow})
			set {_el} to {_base} ~ {_v}
			set {_color} to a random element out of {_colors.dust::*}
			set {_size} to a random number between 2.5 and 3.2
			spawnParticle_Dust({_color}, {_size}, {_el})
	
	set {_addm} to 0.2
	set {_countx} to 1 / {_addm}
	set {_distance} to distance between {_baseloc.1} and {_baseloc.2}
	set {_count} to round({_distance} * {_countx})
	set {_basevec} to setVector({_baseloc.1}, {_baseloc.2}, 1)
	set {_baseloc} to setDirToVec({_baseloc.1}, {_basevec})
	set {_rotatevec} to getVectorFromYawAxis({_baseloc})
	set {_circle} to 4
	set {_addrad} to 360 / {_circle}
	set {_plusrad} to 10

	set {_m} to 0
	set {_rad} to 0
	loop {_count} times:
		add {_addm} to {_m}
		set {_vec} to {_basevec} * vector({_m}, {_m}, {_m})
		set {_elbase} to {_baseloc} ~ {_vec}
		set {_color} to a random element out of {_colors.dust::*}
		spawnParticle_Dust({_color}, 2.75, {_elbase})

		loop {_circle} times:
			add {_addrad} to {_rad}
			set {_v} to {_rotatevec}
			rotate {_v} around {_basevec} by {_rad}
			set {_el} to {_elbase} ~ {_v}
			set {_color} to a random element out of {_colors.spell::*}
			spawnParticle_SpellDot(instant_effect, {_color}, {_el})

		add  {_plusrad} to {_rad}

local function particleCharge(locs: locations):
	add rgb(15, 15, 15) to {_colors::*}
	add rgb(19, 7, 37) to {_colors::*}
	add rgb(26, 13, 37) to {_colors::*}

	loop {@charge-tick} times:
		for {_l} in {_locs::*}:
			set {_c} to a random integer between 30 and 80
			loop {_c} times:
				set {_c.2} to a random integer between 1 and 3
				set {_p} to a random number between 0.5 and {@effect-radius}
				set {_v} to randomVector({_p})
				set {_block} to a black concrete
				set {_el} to {_l} ~ {_v}
				loop {_c.2} times:
					spawnParticle_Block({_block}, {_el})
		
			set {_c} to a random integer between 50 and 100
			loop {_c} times:
				set {_c.2} to a random integer between 3 and 8
				set {_p} to a random number between 0.5 and {@effect-radius}
				set {_v} to randomVector({_p})
				set {_color} to a random element out of {_colors::*}
				set {_el} to {_l} ~ {_v}
				loop {_c.2} times:
					spawnParticle_Spell(effect, {_color}, 0.5, {_el})
			
			set {_c} to a random integer between 30 and 50
			loop {_c} times:
				set {_p} to a random number between 0.5 and {@effect-radius}
				set {_v} to randomVector({_p})
				set {_el} to {_l} ~ {_v}
				set {_pv} to {_v} * vector(0.1, 0.1, 0.1)
				spawnParticle_Vector(large_smoke, {_pv}, 0.75, {_el})

		wait a tick

local function particleExplosion(loc: location):
	add rgb(18, 7, 49) to {_colors::*}
	add rgb(10, 6, 70) to {_colors::*}
	add rgb(18, 29, 63) to {_colors::*}

	set {_count} to a random integer between 100 and 130
	loop {_count} times:
		set {_v} to randomVector()
		spawnParticle_Vector(sculk_soul, {_v}, 0.25, {_loc})
	
	set {_count} to a random integer between 30 and 50
	loop {_count} times:
		set {_p} to a random number between 0.5 and {@effect-radius}
		set {_v} to randomVector({_p})
		set {_el} to {_loc} ~ {_v}
		spawnParticle(sonic_boom, {_el})
	
	set {_count} to a random integer between 50 and 100
	loop {_count} times:
		set {_p} to a random number between 0.5 and {@effect-radius}
		set {_v} to randomVector({_p})
		set {_el} to {_loc} ~ {_v}
		set {_color} to a random element out of {_colors::*}
		set {_size} to a random number between 3 and 3.5
		spawnParticle_Dust({_color}, {_size}, {_el})
	
	set {_count} to a random integer between 100 and 130
	loop {_count} times:
		set {_p} to a random number between 0.5 and {@effect-radius}
		set {_v} to randomVector({_p})
		set {_el} to {_loc} ~ {_v}
		set {_rv} to {_v} * vector(0.1, 0.1, 0.1)
		spawnParticle_Vector(soul_fire_flame, {_rv}, 0.3, {_el})

local function particleCursed(entity: entity):
	set {_count} to a random integer between 20 and 30
	set {_block} to a black concrete
	loop {_count} times:
		set {_el} to aroundEffect({_entity})
		spawnParticle_BlockData(dust_pillar, {_block}, {_el})

local function soundCounting(player: player, target: player):
	playSound("entity.wither.hurt", 5, 1, {_player})
	playSound("entity.wither.hurt", 5, 1, {_tg})

local function soundCharge(locs: locations):
	for {_l} in {_locs::*}:
		playSound("entity.wither.ambient", 1, 0.65, {_l})

local function soundExplosion(loc: location):
	playSound("entity.wither.death", 2, 0.5, {_loc})

local function soundCursed(entity: entity):
	playSound("entity.wither_skeleton.hurt", 1, 1.35, {_entity})