# Voodoo Doll

import:
	com.destroystokyo.paper.entity.Pathfinder
	com.destroystokyo.paper.entity.Pathfinder$PathResult

options:
	data-voodoo-player: "voodoodoll-player"
	data-voodoo-time: "voodoodoll-time"

	effect-tick: 600

function kitEffect_VoodooDoll(player: player):
	set {_SkillTarget} to getKitStats({_player}, "SkillTarget")
	if {_SkillTarget} is not set:
		send action bar "§c§l対象が存在しません!" to {_player}
		stop

	if kitCheckSpirit({_player}, "Voodoo Doll") is false:
		stop

	nameCT({_player}, "Voodoo Doll")
	if getKitStats({_player}, "VoodooDoll") is set:
		deleteKitStats({_player}, "VoodooDoll")
		loop all entities:
			type of loop-entity is an armor stand
			getGameType(loop-entity) is "Kit"
			getPersistentData(loop-entity, {@data-voodoo-player}) is "%{_player}%"
			delete loop-entity
	set {_tg} to {_SkillTarget}
	set {_memsg} to kitGhostMessage("§5%{_tg}% §2の藁人形を生成した...", true)
	set {_youmsg} to kitGhostMessage("§4自分の藁人形が作成された! §6壊しに行こう!", true)
	kitMsg({_player}, {_memsg})
	message formatted {_youmsg} to {_tg}
	kitEffectDescription({_tg}, "§5§l藁人形の呪術")
	playSound("entity.villager.work_fletcher", 1, 0.5, {_player})
	set {_armorloc} to location of {_player}
	set {_now} to now
	spawn an armor stand at location of {_player}
	setGameType(spawned armor stand)
	setPersistentData(spawned armor stand, {@data-voodoo-player}, "%{_player}%")
	setPersistentData(spawned armor stand, {@data-voodoo-time}, "%{_now}%")
	set helmet of spawned armor stand to skull of {_tg}
	setKitStats({_player}, "VoodooDoll", {_now})
	set {_vector} to setVector(location of {_tg}, location of {_player})
	set {_effbaseloc} to location of head of {_tg}
	set yaw of {_effbaseloc} to yaw of {_vector}
	set pitch of {_effbaseloc} to pitch of {_vector}
	set {_t} to round(distance between {_player} and {_tg})
	loop {_t} times:
		set {_el} to location loop-number meters in front of {_effbaseloc}
		spawnParticle(end_rod, {_el})
	
	loop {@effect-tick} times:
		continue if getKitStats({_player}, "VoodooDoll") is not {_now}

		delete {_exist}
		if hasPotionEffect({_tg}, wither) is false:
			applyEffect({_tg}, wither, 1, {@effect-tick})

		loop all entities:
			type of loop-entity is an armor stand
			getGameType(loop-entity) is "Kit"
			getPersistentData(loop-entity, {@data-voodoo-player}) is "%{_player}%"
			getPersistentData(loop-entity, {@data-voodoo-time}) is "%{_now}%"
			set {_exist} to true
			set {_armortarget} to loop-entity
			set {_id} to id of loop-entity
			set {_el} to aroundEffect(loop-entity)
			spawnParticle(soul, {_el})

		if {Class::%{_tg}%} is not set:
			delete {_exist}
			deleteKitStats({_player}, "VoodooDoll")
		if {_exist} is true:
			packetGlowing({_tg}, {_armortarget})
		else:
			packetUnglowing({_tg}, {_armortarget})
			deleteKitStats({_player}, "VoodooDoll")
		wait a tick
	removePotionEffect({_tg}, wither)
	loop all entities:
		type of loop-entity is an armor stand
		getGameType(loop-entity) is "Kit"
		getPersistentData(loop-entity, {@data-voodoo-player}) is "%{_player}%"
		getPersistentData(loop-entity, {@data-voodoo-time}) is "%{_now}%"
		delete loop-entity

on damage of armor stand:
	attacker is set
	getPersistentData(victim, {@data-voodoo-player}) is set
	set {_player} to getPersistentData(victim, {@data-voodoo-player}) parsed as player
	if kitCheckTeam(attacker, {_player}, false) is true:
		deleteKitStats({_player}, "VoodooDoll")
		set {_memsg} to kitGhostMessage("§5藁人形が破壊された!", true)
		kitMsg({_player}, {_memsg})
		delete victim