# Knightのスキル Ver1.0.0

# Weapons
# function kitWeapon_Knight_1(player: player):
# 	kitEffect_Sword({_player})

function kitWeapon_Knight_2(player: player):
	kitEffect_Cutlass({_player})

# function kitWeapon_Knight_3(player: player):
# 	kitEffect_Excalibur({_player})

# Skills
function kitSkill_Knight_1(player: player):
	kitEffect_DeflectiveSweep({_player})

function kitSkill_Knight_2(player: player):
	kitEffect_KnightChanger({_player})

function kitSkill_Knight_3(player: player):
	kitEffect_SummonHorse({_player})

function kitSkill_Knight_4(player: player):
	kitEffect_CallingSoldiers({_player})

function kitSkill_Knight_5(player: player):
	kitEffect_JusticePower({_player})

function kitSkill_Knight_6(player: player):
	kitEffect_HerosCourage({_player})

function kitSkill_Knight_7(player: player):
	kitEffect_ReligiousShelter({_player})

function kitSkill_Knight_8(player: player):
	kitEffect_GloriousHonor({_player})

# Timer
function kitTimerKnight(player: player):
	if kitSelectChecker_Weapon({_player}, "Knight") is not 3:
		stop
	while {Class::%{_player}%} is "Knight":
		kitEffect_Excalibur_Glow({_player})
		wait a second