# Passive
options:
	berserk-range: 6
	berserk-damage: 1

on damage of player:
	damage was caused by attack
	set {_attacker} to getAttacker(victim)
	getKitStats({_attacker}, "AdrenalinRage") is not set
	set {_enable} to false

	if getKitStats({_attacker}, "Berserk") is true:
		set {_enable} to true
		set {_range} to {@berserk-range}
		set {_damage} to {@berserk-damage}
	if getKitStats({_attacker}, "BerserkTime") is set:
		set {_enable} to true
		set {_range} to kitEffect_BerserkTime_GetRadius()
		set {_damage} to kitEffect_BerserkTime_GetDamage()
		playSound("entity.blaze.shoot", 0.75, 1.75, {_attacker})

	if {_enable} is false:
		stop

	kitParticle_Berserk_Around({_attacker}, {_range})
	loop all players in radius {_range} around {_attacker}:
		loop-player is not {_attacker}
		loop-player is not victim
		kitDamageNull({_attacker}, loop-player, {_damage}, "乱撃")
		kitEffectDescription(victim, "§4❤%{_damage}%")
		kitParticle_Berserk_Hit(loop-player, {_damage})

local function kitParticle_Berserk_Around(player: player, range: number):
	set {_baseloc} to location 1 meter above {_player}
	loop 20 times:
		add 360 / 20 to {_rad}
		set {_el} to {_baseloc}
		add {_range} * sin({_rad}) to x of {_el}
		add {_range} * cos({_rad}) to z of {_el}
		spawnParticle(raid_omen, {_el})

local function kitParticle_Berserk_Hit(player: player, damage: number):
	set {_baseloc} to location 1 meter above {_player}
	loop 3 * {_damage} times:
		set {_v} to randomVector()
		spawnParticle_Vector(damage_indicator, {_v}, 1, {_baseloc})


# Timer
function kitTimerBerserker(player: player):
	setKitStats({_player}, "NoSupport", true)
	setKitStats({_player}, "Berserk", true)
	while {Class::%{_player}%} is "Berserker":
		# Berserk - weakness
		set {_range} to {@berserk-range}
		if getKitStats({_player}, "BerserkTime") is set:
			set {_range} to kitEffect_BerserkTime_GetRadius()

		set {_exist} to false
		loop all players in radius {_range} around {_player}:
			loop-player is not {_player}
			set {_exist} to true

		if {_exist} is false:
			applyEffect({_player}, weakness, 3, 20, true)
			kitParticle_InsaneLimiter({_player})

		wait a second

local function kitParticle_InsaneLimiter(player: player):
	loop 20 times:
		set {_el} to aroundEffect({_player})
		add 0.5 to y of {_el}
		set {_v} to vector(0, -0.5, 0)
		spawnParticle_Vector(trial_spawner_detection_ominous, {_v}, 0.5, {_el})
		wait a tick