options:
	prefix: §2[%{CLS::%player%}%]
	attackprefix: §2[%{CLS::%attacker%}%]
	victimprefix: §2[%{CLS::%victim%}%]
	shootprefix: §2[%{CLS::%shooter%}%]

aliases:
	allowbridge = air, water, lava

# Lumberjackのスキル Ver1.0.0
on rightclick holding a 336:
	name of player's tool is "§6Soften Armor"
	cancel event
	if {CT.%player%::%name of player's tool%} is not set:
		set {CT.%player%::%name of player's tool%} to 40
		set {-Stats.%player%::SoftenArmor} to true
		message "{@prefix} §9防具が壊しやすくなります..."
		play raw sound "random.pop" at player with pitch 0.5 volume 1
		drawDot count 5, particle "redstone", RGB 255, 165, 0, center player, visibleRange 30, keepFor 10 seconds
		wait 10 seconds
		delete {-Stats.%player%::SoftenArmor}
		message "{@prefix} §1効果が切れました"
	else:
		set action bar of player to "§c§lクールタイムが終わっていません!"

on damage:
	if {-Stats.%attacker%::SoftenArmor} is true:
		drawDot count 5, particle "itemcrack", material helmet of victim, center victim, visibleRange 30
		add 10 to data value of helmet of victim
		drawDot count 5, particle "itemcrack", material chestplate of victim, center victim, visibleRange 30
		add 10 to data value of chestplate of victim
		drawDot count 5, particle "itemcrack", material leggings of victim, center victim, visibleRange 30
		add 10 to data value of leggings of victim
		drawDot count 5, particle "itemcrack", material boots of victim, center victim, visibleRange 30
		add 10 to data value of boots of victim
		play raw sound "random.break" at victim with pitch 0.5 volume 1
	else if attacker's tool is {AxeSave::SpringFortune}:
		chance of 50%:
			drawDot count 1, particle "itemcrack", material helmet of victim, center victim, visibleRange 30
			add 10 to data value of helmet of victim
			play raw sound "random.break" at victim with pitch 0.5 volume 0.5
		chance of 50%:
			drawDot count 1, particle "itemcrack", material chestplate of victim, center victim, visibleRange 30
			add 10 to data value of chestplate of victim
			play raw sound "random.break" at victim with pitch 0.5 volume 0.5
		chance of 50%:
			drawDot count 1, particle "itemcrack", material leggings of victim, center victim, visibleRange 30
			add 10 to data value of leggings of victim
			play raw sound "random.break" at victim with pitch 0.5 volume 0.5
		chance of 50%:
			drawDot count 1, particle "itemcrack", material boots of victim, center victim, visibleRange 30
			add 10 to data value of boots of victim
			play raw sound "random.break" at victim with pitch 0.5 volume 0.5
	else if attacker's tool is {AxeSave::GoldAxe}:
		drawDot count 1, particle "itemcrack", material gold ingot, center victim, visibleRange 30
		add 20 to data value of helmet of victim
		add 20 to data value of chestplate of victim
		add 20 to data value of leggings of victim
		add 20 to data value of boots of victim
		play raw sound "random.break" at victim with pitch 1.2 volume 1
		chance of 30%:
			heal attacker by 1 heart
	else if attacker's tool is {AxeSave::SilverAxe}:
		loop all players in radius 5 around victim:
			{TrueTeam::%loop-player%} is not {TrueTeam::%attacker%}
			loop-player is not victim
			set {LastKiller::%loop-player%} to attacker
			add attacker to {damager.%loop-player%::*}
			damage loop-player by 4 hearts
		chance of 80%:
			drawDot count 1, particle "itemcrack", material helmet of victim, center victim, visibleRange 30
			add 8 to data value of helmet of victim
			play raw sound "random.break" at victim with pitch 1 volume 0.5
		chance of 80%:
			drawDot count 1, particle "itemcrack", material chestplate of victim, center victim, visibleRange 30
			add 8 to data value of chestplate of victim
			play raw sound "random.break" at victim with pitch 1 volume 0.5
		chance of 80%:
			drawDot count 1, particle "itemcrack", material leggings of victim, center victim, visibleRange 30
			add 8 to data value of leggings of victim
			play raw sound "random.break" at victim with pitch 1 volume 0.5
		chance of 80%:
			drawDot count 1, particle "itemcrack", material boots of victim, center victim, visibleRange 30
			add 8 to data value of boots of victim
			play raw sound "random.break" at victim with pitch 1 volume 0.5
	else if attacker's tool is {AxeSave::TatteredAxe}:
		chance of 10%:
			execute console command "/blood %victim%"
	else:
		{CLS::%attacker%} is "LUM"
		chance of 30%:
			drawDot count 1, particle "itemcrack", material helmet of victim, center victim, visibleRange 30
			add 10 to data value of helmet of victim
			play raw sound "random.break" at victim with pitch 5 volume 0.5
		chance of 30%:
			drawDot count 1, particle "itemcrack", material chestplate of victim, center victim, visibleRange 30
			add 10 to data value of chestplate of victim
			play raw sound "random.break" at victim with pitch 5 volume 0.5
		chance of 30%:
			drawDot count 1, particle "itemcrack", material leggings of victim, center victim, visibleRange 30
			add 10 to data value of leggings of victim
			play raw sound "random.break" at victim with pitch 5 volume 0.5
		chance of 30%:
			drawDot count 1, particle "itemcrack", material boots of victim, center victim, visibleRange 30
			add 10 to data value of boots of victim
			play raw sound "random.break" at victim with pitch 5 volume 0.5
		set {_b} to 1
		if helmet of victim is not air:
			subtract 0.05 from {_b}
		if chestplate of victim is not air:
			subtract 0.05 from {_b}
		if leggings of victim is not air:
			subtract 0.05 from {_b}
		if boots of victim is not air:
			subtract 0.05 from {_b}
		set damage to damage * {_b}

on rightclick holding a 334:
	name of player's tool is "§dStrip Skin"
	cancel event
	if {CT.%player%::%name of player's tool%} is not set:
		set {_tg} to target player
		if {_tg} is set:
			if {team::%{_tg}%} is not {team::%player%}:
				set {CT.%player%::%name of player's tool%} to 50
				set {-Stats.%{_tg}%::StripSkin} to true
				message "{@prefix} §6%{_tg}% §eの防具を5秒間消去します!"
				message "§c防具が消されてしまった!" to {_tg}
				set {_he} to helmet of {_tg}
				set {_ch} to chestplate of {_tg}
				set {_le} to leggings of {_tg}
				set {_bo} to boots of {_tg}
				set helmet of {_tg} to air
				set chestplate of {_tg} to air
				set leggings of {_tg} to air
				set boots of {_tg} to air
				play raw sound "mob.irongolem.throw" at {_tg} with pitch 0.5 volume 1
				wait 5 seconds
				{-Stats.%{_tg}%::StripSkin} is true
				set helmet of {_tg} to {_he}
				set chestplate of {_tg} to {_ch}
				set leggings of {_tg} to {_le}
				set boots of {_tg} to {_bo}
				message "§c防具がもとに戻った!" to {_tg}
			else:
				set action bar of player to "§c§l味方には発動できません!"
		else:
			set action bar of player to "§c§l目先にプレイヤーがいません!"
	else:
		set action bar of player to "§c§lクールタイムが終わっていません!"

on rightclick holding a 385:
	name of player's tool is "§4Breakable Bomb"
	cancel event
	if {CT.%player%::%name of player's tool%} is not set:
		set {CT.%player%::%name of player's tool%} to 40
		message "{@prefix} §4周辺の敵の防具耐久値を減らす弾を発射しました..."
		play raw sound "mob.ghast.fireball" at player with pitch 1.5 volume 1
		shoot a small fireball at speed 1
		set metadata value "break" of shot projectile to "true"
		drawDot count 3, particle "mobspell", RGB 255, 165, 0, center shot entity, visibleRange 30, keepFor 1 second
	else:
		set action bar of player to "§c§lクールタイムが終わっていません!"

on damage:
	projectile is a small fireball
	metadata value "break" of projectile is "true"
	cancel event

on projectile hit:
	projectile is a small fireball
	metadata value "break" of projectile is "true"
	make a fake explosion at projectile
	play raw sound "mob.zombie.remedy" at projectile with pitch 1 volume 1
	loop all players in radius 5 around projectile:
		{team::%loop-player%} is not {team::%shooter%}
		message "{@shootprefix} §b%loop-player% §6の防具を削りました!" to shooter
		message "§6防具の耐久値が大幅に削られた!" to loop-player
		make a fake explosion at loop-player
		add 30 to data value of helmet of loop-player
		add 30 to data value of chestplate of loop-player
		add 30 to data value of leggings of loop-player
		add 30 to data value of boots of loop-player

on rightclick holding a 280:
	name of player's tool is "§6Fallen Tree"
	cancel event
	if {CT.%player%::%name of player's tool%} is not set:
		set {CT.%player%::%name of player's tool%} to 50
		message "{@prefix} §6木を前方に切り倒します!"
		set {_face} to location of player
		set {_base} to location of block at player
		loop 10 times:
			if block above {_base} is air:
				set {_base} to location of block above {_base}
		set {_y} to y-coordinate of {_base}
		loop 10 times:
			set {_n} to loop-number
			set {_fb} to location of block {_n} blocks in front of {_face}
			set y-coordinate of {_fb} to {_y}
			spawn a falling oak log at location of {_fb}
			set metadata value "falltree" of spawned entity to "%player%"
			play raw sound "dig.wood" at location of {_fb} with pitch 1 volume 1
			drawDot count 1, particle "blockcrack", material oak log, center spawned entity, visibleRange 30, keepFor 3 seconds
			wait a tick
		loop all blocks in radius 2.5 around location of {_fb}:
			loop-block is air
			y-coordinate of loop-block is {_y}
			spawn a falling oak leaves at location of loop-block
			set metadata value "fallleave" of spawned entity to "%player%"
			drawDot count 1, particle "blockcrack", material oak leaves, center spawned entity, visibleRange 30, keepFor 3 seconds
		play raw sound "dig.grass" at location of {_fb} with pitch 1 volume 1
		loop 100 times:
			loop all falling oak logs:
				metadata value "falltree" of loop-falling oak log is "%player%"
				loop all players in radius 2 around loop-falling oak log:
					{team::%loop-player%} is not {team::%player%}
					{_hit.%loop-player%} is not set
					set {_hit.%loop-player%} to true
					make player damage loop-player by 8
					add 20 to data value of helmet of loop-player
					add 20 to data value of chestplate of loop-player
					add 20 to data value of leggings of loop-player
					add 20 to data value of boots of loop-player
					play raw sound "dig.wood" at loop-player with pitch 0.5 volume 1
					delete loop-falling oak log
			loop all falling oak leaves:
				metadata value "fallleave" of loop-falling oak leaves is "%player%"
				loop all players in radius 2 around loop-falling oak leaves:
					{team::%loop-player%} is not {team::%player%}
					{_hit.%loop-player%} is not set
					set {_hit.%loop-player%} to true
					make player damage loop-player by 4
					apply poison 1 to loop-player for 5 seconds
					play raw sound "dig.grass" at loop-player with pitch 2 volume 1
					delete loop-falling oak leaves
			wait a tick
	else:
		set action bar of player to "§c§lクールタイムが終わっていません!"

on rightclick holding a 264:
	name of player's tool is "§bSpring Fortune"
	cancel event
	if {CT.%player%::%name of player's tool%} is not set:
		set {CT.%player%::%name of player's tool%} to 50
		message "{@prefix} §b泉の加護を受け,素晴らしい斧を受け取った!"
		apply slowness 1 to player for 10 seconds
		set {-Stats.%player%::SpringFortune} to true
		play raw sound "random.splash" at player with pitch 1 volume 1
		drawDot count 3, particle "mobspell", RGB 0, 255, 255, center player, visibleRange 30, keepFor 10 seconds
		set {_tool} to slot 0 of player
		set slot 0 of player to {AxeSave::SpringFortune}
		loop 200 times:
			if type of player's tool is diamond axe:
				apply regeneration 1 to player for a tick
			wait a tick
		if {-Stats.%player%::SpringFortune} is true:
			if {Class::%player%} is "Lumberjack":
				set slot 0 of player to {_tool}
				message "{@prefix} §9泉の加護は消え去った..."
	else:
		set action bar of player to "§c§lクールタイムが終わっていません!"

command /axesave <text>:
	permission: sk.admin
	trigger:
		set {AxeSave::%arg 1%} to player's tool
		message "§6Axe§bを§a%arg 1%§bでセーブしました"