import:
	net.kyori.adventure.text.Component
	net.kyori.adventure.text.ObjectComponent
	net.kyori.adventure.text.object.ObjectContents
	net.kyori.adventure.text.object.PlayerHeadObjectContents

# このAPIでの返り値はすべて「Component」

function getTextPlayerHead(player: player) :: object:
	set {_uuid} to {_player}.getUniqueId()
	set {_object} to  ObjectContents.playerHead({_uuid})

	set {_ObjectComponent} to Component.object({_object})

	return {_ObjectComponent}
