# Phantom Dagger

function kitWeapon_Assassin_5(player: player):
	if {Kit-Invisible::%{_player}%} is not set:
		setCT({_player}, name of {_player}'s tool, 20, false)
		kitInvisible({_player}, 3 seconds)
		set {Stats.%{_player}%::PhantomDagger} to true
		playSound("entity.phantom.ambient", 0.7, 2, {_player})
		wait 3 seconds
		delete {Stats.%{_player}%::PhantomDagger}
	else:
		send action bar "§c§l既に透明化しています" to {_player}