function kitUseCounting(player: player, kit: text):
	set {_countid} to a random UUID
	add {_countid} to {Kit-GameInfo.Counts::*}

	set {_count.UUID} to uuid of {_player}
	set {_count.kit} to {_kit}
	set {_count.now} to now
	set {Kit-GameInfo.count-player::%{_countid}%} to {_count.UUID}
	set {Kit-GameInfo.count-kit::%{_countid}%} to {_count.kit}
	set {Kit-GameInfo.count-time::%{_countid}%} to {_count.now}