import:
    java.lang.Runnable

on rightclick:
	metadata value "gametype" of player is "Kit"
	set {_item} to player's tool
	set {_itemkit} to kitItemKitChecker({_item})
	if {_itemkit} is not set:
		stop

	set {_itemtype} to kitItemTypeChecker({_item})
	if {_itemtype} is not set:
		stop

	set {_func::run} to function reference "kit%{_itemtype}%%{_itemkit}%" called with (player)
	set {_interact} to new proxy instance of Runnable using {_func::*}
	{_interact}.run()