# Mace

on damage of player:
	set {_attacker} to getAttacker(victim)
	metadata value "gametype" of {_attacker} is "Kit"
	damage was caused by attack
	{Class::%{_attacker}%} is "Defender"
	set {_tool} to {_attacker}'s tool
	kitItemAllChecker({_tool}, "Defender", "Weapon.main", 2) is true
	{_attacker} is sneaking
	playSound("entity.iron_golem.damage", 1, 1, victim)
	kitStun(victim, 10)
	loop 10 times:
		set {_el} to aroundEffect(victim)
		spawnParticle_Block(dirt, {_el})