# Mace

on damage of player:
	metadata value "gametype" of attacker is "Kit"
	damage was caused by attack
	{Class::%attacker%} is "Defender"
	set {_tool} to attacker's tool
	kitItemAllChecker({_tool}, "Defender", "Weapon.main", 3) is true
	attacker is sneaking
	playSound("entity.iron_golem.damage", 1, 1, victim)
	kitStun(victim, 0.5 seconds)
	loop 10 times:
		set {_el} to aroundEffect(victim)
		spawnParticle_Block(dirt, {_el})