function LastKiller(victim: entity, attacker: player):
	if type of {_victim} is a player:
		set {LastKiller::%{_victim}%} to {_attacker}
		if {damager.%{_victim}%::*} does not contain {_attacker}:
			add {_attacker} to {damager.%{_victim}%::*}

function setSupporter(player: entity, supporter: player):
	if {_player} is not {_supporter}:
		if type of {_player} is a player:
			if {supporter.%{_player}%::*} does not contain {_supporter}:
				add {_supporter} to {supporter.%{_player}%::*}