function drawCount(player: player) :: number:
	add 1 to {EffectCount::%{_player}%}
	return {EffectCount::%{_player}%}

function aroundEffect(player: entity, dis: number = 1) :: location:
	set {_loc} to location of {_player}
	add a random number between {_dis} * -1 and {_dis} to x-coordinate of {_loc}
	add a random number between 0 and {_dis} * 2 to y-coordinate of {_loc}
	add a random number between {_dis} * -1 and {_dis} to z-coordinate of {_loc}
	return {_loc}