function playSound(sound: text, volume: number, pitch: number, location: object, personal: boolean = false):
	if {_personal} is true:
		play sound {_sound} with volume {_volume} with pitch {_pitch} to {_location}
	else:
		play sound {_sound} with volume {_volume} with pitch {_pitch} at {_location}

function scalePitch(scale: number) :: number:
	set {_multiple} to {_scale} - 12
	set {_pitch} to 2 ^ ({_multiple} / 12)
	return {_pitch}