function gameMsg(game: text, msg: text):
	loop all players:
#		{Join::%loop-player%} is {_game}
		message formatted {_msg} to loop-player

function joinPlayerMsg(game: text, msg: text):
	loop all players:
		{Join::%loop-player%} is {_game}
		message formatted {_msg} to loop-player

function staffMsg(msg: text):
	loop all players:
		loop-player has permission "sk.admin"
		message formatted {_msg} to loop-player