function sendTitle(players: players, title: text, subtitle: text, time: time span, fadein: time span, fadeout: time span):
	reset title of {_players::*}
	send title {_title} with subtitle {_subtitle} to {_players::*} for {_time} with fade in {_fadein} with fade out {_fadeout}

function sendSubtitle(players: players, subtitle: text, time: time span, fadein: time span, fadeout: time span):
	reset title of {_players::*}
	send title "" with subtitle {_subtitle} to {_players::*} for {_time} with fade in {_fadein} with fade out {_fadeout}