function chargeActionBar(player: player, active: number, max: number, active.color: text = "<##00ff00>", inactive.color: text = "<##808080>", bracket.color: text = "<##ffd700>"):
	set {_line} to ""
	loop {_max} times:
		if loop-number <= {_active}:
			set {_line} to "%{_line}%%{_active.color}%|"
		else:
			set {_line} to "%{_line}%%{_inactive.color}%|"
	set {_line} to "%{_bracket.color}%[§r %{_line}% %{_bracket.color}%]§r"
	send action bar {_line} to {_player}