function kitDeathEvent_TDM(attacker: player, victim: player, supporters: players):
	# Death情報の更新
	set {_team.victim} to {TrueTeam::%{_victim}%}  # teamの保存
	add 1 to {Kit-Death.personal::%{_victim}%}
	# Victim Scoreboard更新
	set {_kill.victim} to {Kit-Kill.personal::%{_victim}%}
	set {_kill.victim} to 0 if {_kill.victim} is not set
	set {_death.victim} to {Kit-Death.personal::%{_victim}%}
	set {_death.victim} to 0 if {_death.victim} is not set
	kitScorePersonal({_victim}, 1, "§4%{_kill.victim}% §7/ §1%{_death.victim}%")
	# Team Deathの更新
	add 1 to {Kit-Death.team::%{_team.victim}%}
	# victim K/Dの更新
	set {Kit-KD.personal::%{_victim}%} to {Kit-Kill.personal::%{_victim}%} / {Kit-Death.personal::%{_victim}%}

	# Kill情報の更新
	set {_team.attacker} to {TrueTeam::%{_attacker}%}  # teamの保存
	add 1 to {Kit-Kill.personal::%{_attacker}%}
	# Attacker Scoreboard更新
	set {_kill.attacker} to {Kit-Kill.personal::%{_attacker}%}
	set {_kill.attacker} to 0 if {_kill.attacker} is not set
	set {_death.attacker} to {Kit-Death.personal::%{_attacker}%}
	set {_death.attacker} to 0 if {_death.attacker} is not set
	kitScorePersonal({_attacker}, 1, "§4%{_kill.attacker}% §7/ §1%{_death.attacker}%")
	# attacker K/Dの更新
	set {Kit-KD.personal::%{_attacker}%} to {Kit-Kill.personal::%{_attacker}%} / {Kit-Death.personal::%{_attacker}%}
	# Team Pointの設定
	add {Kit-TeamBuff::%{_team.attacker}%} to {Kit-Kill.team::%{_team.attacker}%}
	if {_team.attacker} is "red":
		kitScoreGlobal(9, "§c赤§7: §6%floor({Kit-Kill.team::red})%")
	else if {_team.attacker} is "blue":
		kitScoreGlobal(8, "§9青§7: §6%floor({Kit-Kill.team::blue})%")
	else if {_team.attacker} is "yellow":
		kitScoreGlobal(7, "§e黄§7: §6%floor({Kit-Kill.team::yellow})%")
	else if {_team.attacker} is "green":
		kitScoreGlobal(6, "§a緑§7: §6%floor({Kit-Kill.team::green})%")
	if {Kit-Kill.team::%{_team.attacker}%} >= {Kit-GameStage::goal}:
		add {_team.attacker} to {Kit-WinTeam::*}
		gameMsg("Kit", "§c§l試合終了!")
		stopTimer("Kit-TDM")