# Electro Magic

function kitSkill_Wizard_4(player: player):
	set {_mana} to kitManaCalc({_player}, 10)
	if {Kit-Mana::%{_player}%} >= {_mana}:
		toolCT({_player}, "Wizard", 4)
		shoot a snowball from {_player} at speed 1
		set metadata value "magic" of shot snowball to "electro"
		kitParticle_Wizard_Magic(shot snowball, 100, 100, 0)
		subtract {_mana} from {Kit-Mana::%{_player}%}
	else:
		send action bar "§4§lマナが足りません!" to {_player}