# Dark Magic

function kitSkill_Wizard_2(player: player):
	set {_mana} to kitManaCalc({_player}, 10)
	if {Kit-Mana::%{_player}%} >= {_mana}:
		toolCT({_player}, "Wizard", 2)
		shoot a snowball from {_player} at speed 1
		set metadata value "magic" of shot snowball to "dark"
		kitParticle_Wizard_Magic(shot snowball, 0, 0, 0)
		subtract {_mana} from {Kit-Mana::%{_player}%}
	else:
		send action bar "§4§lマナが足りません!" to {_player}