# Weapon-Name: Fay Stick

on damage of player with priority LOW:
	if {Class::%attacker%} is "Paladin":
		damage was caused by attack
		set {_attacker} to getAttacker(victim)
		set {_tool} to {_attacker}'s tool
		kitItemAllChecker({_tool}, "Paladin", "Weapon.main", 2) is true
		kitCheckAlive(attacker) is true
		if {_attacker} is sneaking:
			kitHeal({_attacker}, 0.5)
		else:
			{_attacker} does not have regeneration
			applyEffect({_attacker}, regeneration, 1, 3 seconds)