allow-click:
- oak_button
- spruce_button
- birch_button
- jungle_button
- acacia_button
- dark_oak_button
- mangrove_button
- cherry_button
- pale_oak_button
- bamboo_button
- crimson_button
- warped_button
- stone_button
- polished_blackstone_button
- lever
- oak_door
- spruce_door
- birch_door
- jungle_door
- acacia_door
- dark_oak_door
- mangrove_door
- cherry_door
- pale_oak_door
- bamboo_door
- crimson_door
- warped_door
- copper_door
- exposed_copper_door
- weathered_copper_door
- oxidized_copper_door
- waxed_copper_door
- waxed_exposed_copper_door
- waxed_weathered_copper_door
- waxed_oxidized_copper_door