# Ghostのスキル Ver1.0.0

# Abilities
on death of player:
	getGameType(victim) is "Kit"
	if {Class::%{-LastKiller::%victim%}%} is "Ghost":
		{Class::%victim%} is not "Ghost"
		getKitStats({-LastKiller::%victim%}, "SpareSoul") is not set
		checkCT({_player}, "Spare Soul") is true
		setKitStats({-LastKiller::%victim%}, "SpareSoul", true)
		setKitStats({-LastKiller::%victim%}, "Resurrection", true)
		set {_memsg} to kitGhostMessage("§5魂を補充しました...", true)
		kitMsg({-LastKiller::%victim%}, {_memsg})
	if getKitStats(victim, "SpareSoul") is true:
		set {_memsg} to kitGhostMessage("§5魂の復活を行いました...", true)
		kitMsg(victim, {_memsg})
		playSound("entity.wither.death", 1, 0.5, victim)
		setCT(victim, "Spare Soul", 10)
		wait 3 ticks
		set slot 1 of victim to air

function kitHasSpareSoul(player: player) :: boolean:
	set {_spare} to getKitStats({_player}, "SpareSoul")
	set {_spare} to false if {_spare} is not set
	return {_spare}

function kitSearchSpiritItem(player: player, name: text) :: item:
	set {_tool} to {_player}'s tool
	set {_toolname} to getItemName({_tool})
	set {_toolname} to unformatted {_toolname}
	set {_skill} to {_tool} if {_toolname} is {_name}

	if {_skill} is not set:
		loop all items in {_player}'s inventory:
			set {_toolname} to getItemName(loop-item)
			set {_toolname} to unformatted {_toolname}
			if {_toolname} is {_name}:
				set {_skill} to loop-item
	stop if {_skill} is not set
	return {_skill}

function kitRequiredSpirit(skill: item) :: number:
	set {_lore::*} to lore of {_skill}
	loop {_lore::*}:
		loop-value contains "§4Spirit§7:"
		set {_spirit} to loop-value
	replace every "§4Spirit§7: §5" with "" in {_spirit}
	set {_spirit} to {_spirit} parsed as number
	return {_spirit}

function kitHasSpirit(player: player, number: number) :: boolean:
	set {_hasSpirit} to kitGetSpirit({_player})
	return true if {_hasSpirit} >= {_number}
	return false

function kitGetSpirit(player: player) :: number:
	return {Kit-Spirits::%{_player}%}

function kitCheckSpirit(player: player, name: text) :: boolean:
	set {_tool} to {_player}'s tool
	set {_toolname} to getItemName({_tool})
	set {_toolname} to unformatted {_toolname}
	set {_skill} to {_tool} if {_toolname} is {_name}

	if {_skill} is not set:
		loop all items in {_player}'s inventory:
			set {_toolname} to getItemName(loop-item)
			set {_toolname} to unformatted {_toolname}
			if {_toolname} is {_name}:
				set {_skill} to loop-item
	return false if {_skill} is not set

	set {_lore::*} to lore of {_skill}
	loop {_lore::*}:
		loop-value contains "§4Spirit§7:"
		set {_spirit} to loop-value
	replace every "§4Spirit§7: §5" with "" in {_spirit}
	set {_spirit} to {_spirit} parsed as number
	if {Kit-Spirits::%{_player}%} >= {_spirit}:
		subtract {_spirit} from {Kit-Spirits::%{_player}%}
		return true

	send action bar "§5§lSpiritが不足しています!" to {_player}
	return false

command /kit-spirit <number> <player=%player%>:
	permission: sk.admin
	trigger:
		set {_player} to arg 2
		set {Kit-Spirits::%{_player}%} to arg 1
		message formatted "§6§l%{_player}% §eの§4Spirit値§eを §9§l%arg 1% §eに設定しました" to player

command /kit-sparesoul <boolean> <player=%player%>:
	permission: sk.admin
	trigger:
		set {_player} to arg 2
		if arg 1 is true:
			setKitStats({_player}, "SpareSoul", true)
			setKitStats({_player}, "Resurrection", true)
			message formatted "§6§l%{_player}% §eの§4Spare Soul§eを§a§l有効化§eしました" to player
			stop
		deleteKitStats({_player}, "SpareSoul")
		deleteKitStats({_player}, "Resurrection")
		message formatted "§6§l%{_player}% §eの§4Spare Soul§eを§c§l無効化§eしました" to player

function kitGhostMessage(text: text, bold: boolean = false) :: text:
	set {_colors::*} to {_text} split at "§"
	set {_finalstring} to ""
	loop {_colors::*}:
		set {_texts::*} to loop-value split at ""
		if {_bold} is true:
			set {_colorcode} to "§%{_texts::1}%§l"
		else:
			set {_colorcode} to "§%{_texts::1}%"
		loop length of loop-value times:
			if loop-number is not 1:
				set {_tx} to {_texts::%loop-number%}
				set {_lct} to "%{_colorcode}%"
				chance of 10%:
					set {_lct} to "%{_lct}%§k"
				set {_lasttext} to "%{_lct}%%{_tx}%"
				set {_finalstring} to "%{_finalstring}%%{_lasttext}%"
	return {_finalstring}

options:
	spirit-timer-prefix: "SpiritTimer-"
	spirit-max-distance: 30

# Timer
function kitTimerGhost(player: player):
	set {Kit-Spirits::%{_player}%} to 0
	set {Kit-NoCorpse::%{_player}%} to true
	startSpiritTimer({_player})

local function startSpiritTimer(player: player):
	set {_timer.id} to getSpiritTimerID({_player})
	create bossbar titled "&4&lSpirit&0: &5&l%{Kit-Spirits::%{_player}%}%" and id {_timer.id} for {_player} with progress {Kit-Spirits::%{_player}%} with colors red with style segmented 10
	while {Class::%{_player}%} is "Ghost":
		delete {_target}
		set {_spiritDistance} to 50
		loop all players in radius {@spirit-max-distance} around {_player}:
			kitCheckTeam(loop-player, {_player}, false) is true
			set {_distance} to distance between {_player} and loop-player
			if {_spiritDistance} > {_distance}:
				set {_spiritDistance} to {_distance}
				set {_target} to loop-player

		if {_spiritDistance} <= 30:
			set {_spirit} to getSpiritGain({_spiritDistance})
			add {_spirit} to {Kit-Spirits::%{_player}%}

			set {_subtract} to getHealthSubtraction({_spiritDistance})
			set {_health} to health of {_target}
			subtract {_subtract} from {_health}
			set health of {_target} to {_health}

			particleSpirit({_player}, {_target}, {_spirit})

		set bossbar {_timer.id} title to "&4&lSpirit&0: &5&l%{Kit-Spirits::%{_player}%}%"
		set bossbar {_timer.id} value to {Kit-Spirits::%{_player}%}
		wait a second
	remove bossbar {_timer.id}

local function getSpiritTimerID(player: player) :: text:
	set {_id} to "{@spirit-timer-prefix}-%{_player}%"
	return {_id}

local function getSpiritGain(distance: number) :: number:
	set {_calc} to {_distance} / 10
	set {_calc} to ceil({_calc})
	set {_calc} to 4 - {_calc}
	return {_calc}

local function getHealthSubtraction(distance: number) :: number:
	set {_calc} to getSpiritGain({_distance})
	set {_calc} to {_calc} * 0.1
	return {_calc}

local function particleSpirit(player: player, target: player, amount: number):
	add rgb(20, 14, 25) to {_colors::*}
	add rgb(19, 3, 40) to {_colors::*}
	add rgb(1, 7, 40) to {_colors::*}

	set {_from} to location 1 meter above {_target}
	set {_to} to location 1 meter above {_player}
	set {_vector} to setVector({_from}, {_to}, 0)

	loop {_amount} times:
		set {_pow} to a random number between 0.5 and 1
		set {_randomV} to randomVector({_pow})
		set {_el} to {_to} ~ {_randomV}
		spawnParticle(soul, {_el})

	set {_tick} to 10 ticks
	set {_count} to {_amount} * 3
	loop {_count} times:
		set {_pow} to a random number between 0 and 1
		set {_randomV} to randomVector({_pow})
		set {_fromEff} to {_from} ~ {_randomV}
		set {_toEff} to {_fromEff} ~ {_vector}
		set {_color} to a random element out of {_colors::*}
		spawnParticle_Trail({_color}, {_toEff}, {_tick}, {_fromEff})