# Disguise Team

function kitSkill_Thief_1(player: player):
	set {_tool} to {_player}'s tool
	remove {_tool} from {_player}
	if type of {_tool} is bonemeal:
		set {_item} to a red dye named "<##FF0000>Disguise Team" with lore lore of {_tool}
		set {_item} to kitItemTagChanger({_item}, "Thief", "Skill", 1)
		kitMsg({_player}, "§c赤チーム §7に擬態した!")
		equip {_player} with leather cap
		dye {_player}'s helmet (255, 0, 0)
		loop 5 times:
			spawnParticle_Dust(rgb(255, 0, 0), 2, aroundEffect({_player}))
		apply invisibility 1 to {_player} for 10 seconds replacing existing effect
		set {team::%{_player}%} to "red"
	else if {_tool} is red dye:
		set {_item} to a blue dye named "<##0000FF>Disguise Team" with lore lore of {_tool}
		set {_item} to kitItemTagChanger({_item}, "Thief", "Skill", 1)
		kitMsg({_player}, "§9青チーム §7に擬態した!")
		equip {_player} with leather cap
		dye {_player}'s helmet (0, 0, 255)
		loop 5 times:
			spawnParticle_Dust(rgb(0, 0, 255), 2, aroundEffect({_player}))
		apply invisibility 1 to {_player} for 10 seconds replacing existing effect
		set {team::%{_player}%} to "blue"
	else if {_tool} is blue dye:
		set {_item} to a yellow dye named "<##FFFF00>Disguise Team" with lore lore of {_tool}
		set {_item} to kitItemTagChanger({_item}, "Thief", "Skill", 1)
		kitMsg({_player}, "§e黄チーム §7に擬態した!")
		equip {_player} with leather cap
		dye {_player}'s helmet (255, 255, 0)
		loop 5 times:
			spawnParticle_Dust(rgb(255, 255, 0), 2, aroundEffect({_player}))
		apply invisibility 1 to {_player} for 10 seconds replacing existing effect
		set {team::%{_player}%} to "yellow"
	else if {_tool} is yellow dye:
		set {_item} to a light green dye named "<##00FF00>Disguise Team" with lore lore of {_tool}
		set {_item} to kitItemTagChanger({_item}, "Thief", "Skill", 1)
		kitMsg({_player}, "§a緑チーム §7に擬態した!")
		equip {_player} with leather cap
		dye {_player}'s helmet (0, 255, 0)
		loop 5 times:
			spawnParticle_Dust(rgb(0, 255, 0), 2, aroundEffect({_player}))
		apply invisibility 1 to {_player} for 10 seconds replacing existing effect
		set {team::%{_player}%} to "green"
	else if {_tool} is light green dye:
		set {_item} to a red dye named "<##FF0000>Disguise Team" with lore lore of {_tool}
		set {_item} to kitItemTagChanger({_item}, "Thief", "Skill", 1)
		kitMsg({_player}, "§c赤チーム §7に擬態した!")
		equip {_player} with leather cap
		dye {_player}'s helmet (255, 0, 0)
		loop 5 times:
			spawnParticle_Dust(rgb(255, 0, 0), 2, aroundEffect({_player}))
		apply invisibility 1 to {_player} for 10 seconds replacing existing effect
		set {team::%{_player}%} to "red"
	give {_item} to {_player}