# Grenade Blaster

on shoot:
	metadata value "gametype" of shooter is "Kit"
	{Class::%shooter%} is "Bomber"
	if projectile is an arrow:
		set {_tool} to shooter's tool
		kitItemAllChecker({_tool}, "Bomber", "Weapon.main", 3) is true
		wait 1 second
#		set {_d} to distance between shooter and projectile
#		{_d} > 5
		set {_l} to location of projectile
		delete projectile
		kitExplosion(shooter, 2, {_l})