# Bowder

on shoot:
	metadata value "gametype" of shooter is "Kit"
	{Class::%shooter%} is "Bomber"
	if projectile is an arrow:
		set {_tool} to shooter's tool
		kitItemAllChecker({_tool}, "Bomber", "Weapon.main", 2) is true
		set {_o} to location of shooter
		loop 3 times:
			wait 5 ticks
			set {_l} to location of projectile
			if {_l} is not {_o}:
				set {_o} to {_l}
				distance between shooter and {_l} > 5
				kitExplosion(shooter, 1, {_l})