disable-worlds:
    Kit-StoneRiver:
        BlockPhysicsEvent:
            blocks:
            - minecraft:water
            - minecraft:flowing_water
        other-events:
        - BlockFromToEvent
        - FluidLevelChangeEvent
    Kit-Volcano:
        EntityChangeBlockEvent:
            entities:
            - falling fire
    Lobby:
        other-events:
        - BlockFromToEvent
        - FluidLevelChangeEvent

