# Reflectorのスキル Ver1.0.0

# Weapons
function kitWeaponReflector(player: player):
	set {_tool} to {_player}'s tool
	set {_item.num} to kitItemNumberChecker({_tool})
	checkCT({_player}, name of {_tool}) is true
	checkItemCT({_player}, {_tool}) is true
	if {_item.num} is 3:
		kitWeapon_Reflector_3({_player})

# Skills
function kitSkillReflector(player: player) :: boolean:
	set {_tool} to {_player}'s tool
	set {_item.num} to kitItemNumberChecker({_tool})
	if checkCT({_player}, name of {_tool}) is true:
		if {_item.num} is 1:
			kitSkill_Reflector_1({_player})
		else if {_item.num} is 2:
			kitSkill_Reflector_2({_player})
		else if {_item.num} is 3:
			kitSkill_Reflector_3({_player})
		else if {_item.num} is 4:
			kitSkill_Reflector_4({_player})
		else if {_item.num} is 5:
			kitSkill_Reflector_5({_player})
		else if {_item.num} is 6:
			kitSkill_Reflector_6({_player})
		else if {_item.num} is 7:
			kitSkill_Reflector_7({_player})
		else if {_item.num} is 8:
			kitSkill_Reflector_8({_player})
	return true

# Ability
on damage of player:
	{Class::%victim%} is "Reflector"
	attacker exists
	kitReflector_DamageChecker(victim) is "none"
	set {_c} to kitPercentDuel(victim, attacker, 20)
	chance of {_c}%:
		set {_dm} to damage / 4
		kitDamage(victim, attacker, {_dm}, true)
		playSound("entity.experience_orb.pickup", 1, 1.5, victim)

function kitReflector_DamageChecker(victim: player) :: text:
	if {Stats.%{_victim}%::DamageAbsorption} is set:
		return "Damage Absorption"
	if {Stats.%{_victim}%::PerfectReflection} is set:
		return "Perfect Reflection"
	return "none"

# Timer
function kitTimerReflector(player: player):
	set {_wn} to kitSelectChecker_Weapon({_player}, "Reflector")
	if {_wn} is not 3:
		stop
	set {Stats.%{_player}%::TolleStone} to 0
	create bossbar titled "&5&lDamage Hoard&b: &d&l%{Stats.%{_player}%::TolleStone}%" and id "%{_player}%-TolleStone" for {_player} with progress {Stats.%{_player}%::TolleStone} with colors purple with style segmented 10
	while {Class::%{_player}%} is "Reflector":
		set bossbar "%{_player}%-TolleStone" title to "&5&lDamage Hoard&b: &d&l%{Stats.%{_player}%::TolleStone}%"
		set bossbar "%{_player}%-TolleStone" value to {Stats.%{_player}%::TolleStone} * 10
		wait a second
	remove bossbar "%{_player}%-TolleStone"